// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: esriPBuffer/graph/ApplyEditsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EsriPBuffer.Graph {

  /// <summary>Holder for reflection information generated from esriPBuffer/graph/ApplyEditsResponse.proto</summary>
  public static partial class ApplyEditsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for esriPBuffer/graph/ApplyEditsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApplyEditsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ciplc3JpUEJ1ZmZlci9ncmFwaC9BcHBseUVkaXRzUmVzcG9uc2UucHJvdG8S",
            "EWVzcmlQQnVmZmVyLmdyYXBoGiZlc3JpUEJ1ZmZlci9ncmFwaC9Fc3JpR3Jh",
            "cGhUeXBlcy5wcm90bxolZXNyaVBCdWZmZXIvT2JqZWN0SWRlbnRpZmllclNl",
            "dC5wcm90byLZAQoLRWRpdFJlc3VsdHMSLQoJb2lkX2FycmF5GAEgASgLMhou",
            "ZXNyaVBCdWZmZXIuT2JqZWN0SWRBcnJheRIWCg5nbG9iYWxpZF9hcnJheRgC",
            "IAEoDBI6CgZlcnJvcnMYAyADKAsyKi5lc3JpUEJ1ZmZlci5ncmFwaC5FZGl0",
            "UmVzdWx0cy5FcnJvcnNFbnRyeRpHCgtFcnJvcnNFbnRyeRILCgNrZXkYASAB",
            "KAQSJwoFdmFsdWUYAiABKAsyGC5lc3JpUEJ1ZmZlci5ncmFwaC5FcnJvcjoC",
            "OAEirQEKHENhc2NhZGluZ1JlbGF0aW9uc2hpcERlbGV0ZXMSQwobcmVsYXRp",
            "b25zaGlwX2RlbGV0ZV9yZXN1bHRzGAEgASgLMh4uZXNyaVBCdWZmZXIuZ3Jh",
            "cGguRWRpdFJlc3VsdHMSJAocb3JpZ2luX2VudGl0eV9nbG9iYWxpZF9hcnJh",
            "eRgCIAEoDBIiChpkZXN0X2VudGl0eV9nbG9iYWxpZF9hcnJheRgDIAEoDCJX",
            "Ch1SZWxhdGlvbnNoaXBUeXBlU2NoZW1hQ2hhbmdlcxIbChNvcmlnaW5fZW50",
            "aXR5X3R5cGVzGAEgAygJEhkKEWRlc3RfZW50aXR5X3R5cGVzGAIgAygJIqkN",
            "ChVHcmFwaEFwcGx5RWRpdHNSZXN1bHQSJwoFZXJyb3IYASABKAsyGC5lc3Jp",
            "UEJ1ZmZlci5ncmFwaC5FcnJvchJaChJlbnRpdHlfYWRkX3Jlc3VsdHMYAiAD",
            "KAsyPi5lc3JpUEJ1ZmZlci5ncmFwaC5HcmFwaEFwcGx5RWRpdHNSZXN1bHQu",
            "RW50aXR5QWRkUmVzdWx0c0VudHJ5EmYKGHJlbGF0aW9uc2hpcF9hZGRfcmVz",
            "dWx0cxgDIAMoCzJELmVzcmlQQnVmZmVyLmdyYXBoLkdyYXBoQXBwbHlFZGl0",
            "c1Jlc3VsdC5SZWxhdGlvbnNoaXBBZGRSZXN1bHRzRW50cnkSYAoVZW50aXR5",
            "X3VwZGF0ZV9yZXN1bHRzGAQgAygLMkEuZXNyaVBCdWZmZXIuZ3JhcGguR3Jh",
            "cGhBcHBseUVkaXRzUmVzdWx0LkVudGl0eVVwZGF0ZVJlc3VsdHNFbnRyeRJs",
            "ChtyZWxhdGlvbnNoaXBfdXBkYXRlX3Jlc3VsdHMYBSADKAsyRy5lc3JpUEJ1",
            "ZmZlci5ncmFwaC5HcmFwaEFwcGx5RWRpdHNSZXN1bHQuUmVsYXRpb25zaGlw",
            "VXBkYXRlUmVzdWx0c0VudHJ5EmAKFWVudGl0eV9kZWxldGVfcmVzdWx0cxgG",
            "IAMoCzJBLmVzcmlQQnVmZmVyLmdyYXBoLkdyYXBoQXBwbHlFZGl0c1Jlc3Vs",
            "dC5FbnRpdHlEZWxldGVSZXN1bHRzRW50cnkSbAobcmVsYXRpb25zaGlwX2Rl",
            "bGV0ZV9yZXN1bHRzGAcgAygLMkcuZXNyaVBCdWZmZXIuZ3JhcGguR3JhcGhB",
            "cHBseUVkaXRzUmVzdWx0LlJlbGF0aW9uc2hpcERlbGV0ZVJlc3VsdHNFbnRy",
            "eRJ/CiVjYXNjYWRpbmdfcmVsYXRpb25zaGlwX2RlbGV0ZV9yZXN1bHRzGAgg",
            "AygLMlAuZXNyaVBCdWZmZXIuZ3JhcGguR3JhcGhBcHBseUVkaXRzUmVzdWx0",
            "LkNhc2NhZGluZ1JlbGF0aW9uc2hpcERlbGV0ZVJlc3VsdHNFbnRyeRJjChdy",
            "ZWxfdHlwZV9zY2hlbWFfY2hhbmdlcxgJIAMoCzJCLmVzcmlQQnVmZmVyLmdy",
            "YXBoLkdyYXBoQXBwbHlFZGl0c1Jlc3VsdC5SZWxUeXBlU2NoZW1hQ2hhbmdl",
            "c0VudHJ5GlcKFUVudGl0eUFkZFJlc3VsdHNFbnRyeRILCgNrZXkYASABKAkS",
            "LQoFdmFsdWUYAiABKAsyHi5lc3JpUEJ1ZmZlci5ncmFwaC5FZGl0UmVzdWx0",
            "czoCOAEaXQobUmVsYXRpb25zaGlwQWRkUmVzdWx0c0VudHJ5EgsKA2tleRgB",
            "IAEoCRItCgV2YWx1ZRgCIAEoCzIeLmVzcmlQQnVmZmVyLmdyYXBoLkVkaXRS",
            "ZXN1bHRzOgI4ARpaChhFbnRpdHlVcGRhdGVSZXN1bHRzRW50cnkSCwoDa2V5",
            "GAEgASgJEi0KBXZhbHVlGAIgASgLMh4uZXNyaVBCdWZmZXIuZ3JhcGguRWRp",
            "dFJlc3VsdHM6AjgBGmAKHlJlbGF0aW9uc2hpcFVwZGF0ZVJlc3VsdHNFbnRy",
            "eRILCgNrZXkYASABKAkSLQoFdmFsdWUYAiABKAsyHi5lc3JpUEJ1ZmZlci5n",
            "cmFwaC5FZGl0UmVzdWx0czoCOAEaWgoYRW50aXR5RGVsZXRlUmVzdWx0c0Vu",
            "dHJ5EgsKA2tleRgBIAEoCRItCgV2YWx1ZRgCIAEoCzIeLmVzcmlQQnVmZmVy",
            "LmdyYXBoLkVkaXRSZXN1bHRzOgI4ARpgCh5SZWxhdGlvbnNoaXBEZWxldGVS",
            "ZXN1bHRzRW50cnkSCwoDa2V5GAEgASgJEi0KBXZhbHVlGAIgASgLMh4uZXNy",
            "aVBCdWZmZXIuZ3JhcGguRWRpdFJlc3VsdHM6AjgBGnoKJ0Nhc2NhZGluZ1Jl",
            "bGF0aW9uc2hpcERlbGV0ZVJlc3VsdHNFbnRyeRILCgNrZXkYASABKAkSPgoF",
            "dmFsdWUYAiABKAsyLy5lc3JpUEJ1ZmZlci5ncmFwaC5DYXNjYWRpbmdSZWxh",
            "dGlvbnNoaXBEZWxldGVzOgI4ARptChlSZWxUeXBlU2NoZW1hQ2hhbmdlc0Vu",
            "dHJ5EgsKA2tleRgBIAEoCRI/CgV2YWx1ZRgCIAEoCzIwLmVzcmlQQnVmZmVy",
            "LmdyYXBoLlJlbGF0aW9uc2hpcFR5cGVTY2hlbWFDaGFuZ2VzOgI4AUIlCh5j",
            "b20uZXNyaS5hcmNnaXMucHJvdG9idWYuZ3JhcGhIA/gBAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EsriPBuffer.Graph.EsriGraphTypesReflection.Descriptor, global::EsriPBuffer.ObjectIdentifierSetReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EsriPBuffer.Graph.EditResults), global::EsriPBuffer.Graph.EditResults.Parser, new[]{ "OidArray", "GlobalidArray", "Errors" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::EsriPBuffer.Graph.CascadingRelationshipDeletes), global::EsriPBuffer.Graph.CascadingRelationshipDeletes.Parser, new[]{ "RelationshipDeleteResults", "OriginEntityGlobalidArray", "DestEntityGlobalidArray" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges), global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges.Parser, new[]{ "OriginEntityTypes", "DestEntityTypes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EsriPBuffer.Graph.GraphApplyEditsResult), global::EsriPBuffer.Graph.GraphApplyEditsResult.Parser, new[]{ "Error", "EntityAddResults", "RelationshipAddResults", "EntityUpdateResults", "RelationshipUpdateResults", "EntityDeleteResults", "RelationshipDeleteResults", "CascadingRelationshipDeleteResults", "RelTypeSchemaChanges" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// For every edit result K:
  ///   - oid_array[K] will hold its OID
  ///   - globalid_array[K * 16 ... (K + 1) * 16 - 1] will hold its GlobalID
  ///   - errors[K] will hold the Error, if any
  ///
  /// If errors[K] is set, then:
  ///   - oid_array[K] == 0
  ///   - globalid_array[K * 16 ... (K + 1) * 16 - 1] == NIL (i.e. all 16 bytes set to zero, representing the NIL UUID: {00000000-0000-0000-0000-000000000000})
  /// </summary>
  public sealed partial class EditResults : pb::IMessage<EditResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EditResults> _parser = new pb::MessageParser<EditResults>(() => new EditResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EsriPBuffer.Graph.ApplyEditsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditResults(EditResults other) : this() {
      oidArray_ = other.oidArray_ != null ? other.oidArray_.Clone() : null;
      globalidArray_ = other.globalidArray_;
      errors_ = other.errors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditResults Clone() {
      return new EditResults(this);
    }

    /// <summary>Field number for the "oid_array" field.</summary>
    public const int OidArrayFieldNumber = 1;
    private global::EsriPBuffer.ObjectIdArray oidArray_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EsriPBuffer.ObjectIdArray OidArray {
      get { return oidArray_; }
      set {
        oidArray_ = value;
      }
    }

    /// <summary>Field number for the "globalid_array" field.</summary>
    public const int GlobalidArrayFieldNumber = 2;
    private pb::ByteString globalidArray_ = pb::ByteString.Empty;
    /// <summary>
    /// `globalid_array` is a concatenation of 1..N RFC4122 UUIDs. Size must be multiple of 16.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString GlobalidArray {
      get { return globalidArray_; }
      set {
        globalidArray_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "errors" field.</summary>
    public const int ErrorsFieldNumber = 3;
    private static readonly pbc::MapField<ulong, global::EsriPBuffer.Graph.Error>.Codec _map_errors_codec
        = new pbc::MapField<ulong, global::EsriPBuffer.Graph.Error>.Codec(pb::FieldCodec.ForUInt64(8, 0UL), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.Error.Parser), 26);
    private readonly pbc::MapField<ulong, global::EsriPBuffer.Graph.Error> errors_ = new pbc::MapField<ulong, global::EsriPBuffer.Graph.Error>();
    /// <summary>
    /// indexed by position in `oid_array`, `globalid_array`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<ulong, global::EsriPBuffer.Graph.Error> Errors {
      get { return errors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OidArray, other.OidArray)) return false;
      if (GlobalidArray != other.GlobalidArray) return false;
      if (!Errors.Equals(other.Errors)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (oidArray_ != null) hash ^= OidArray.GetHashCode();
      if (GlobalidArray.Length != 0) hash ^= GlobalidArray.GetHashCode();
      hash ^= Errors.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oidArray_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OidArray);
      }
      if (GlobalidArray.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(GlobalidArray);
      }
      errors_.WriteTo(output, _map_errors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oidArray_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OidArray);
      }
      if (GlobalidArray.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(GlobalidArray);
      }
      errors_.WriteTo(ref output, _map_errors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (oidArray_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OidArray);
      }
      if (GlobalidArray.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GlobalidArray);
      }
      size += errors_.CalculateSize(_map_errors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditResults other) {
      if (other == null) {
        return;
      }
      if (other.oidArray_ != null) {
        if (oidArray_ == null) {
          OidArray = new global::EsriPBuffer.ObjectIdArray();
        }
        OidArray.MergeFrom(other.OidArray);
      }
      if (other.GlobalidArray.Length != 0) {
        GlobalidArray = other.GlobalidArray;
      }
      errors_.Add(other.errors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (oidArray_ == null) {
              OidArray = new global::EsriPBuffer.ObjectIdArray();
            }
            input.ReadMessage(OidArray);
            break;
          }
          case 18: {
            GlobalidArray = input.ReadBytes();
            break;
          }
          case 26: {
            errors_.AddEntriesFrom(input, _map_errors_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (oidArray_ == null) {
              OidArray = new global::EsriPBuffer.ObjectIdArray();
            }
            input.ReadMessage(OidArray);
            break;
          }
          case 18: {
            GlobalidArray = input.ReadBytes();
            break;
          }
          case 26: {
            errors_.AddEntriesFrom(ref input, _map_errors_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CascadingRelationshipDeletes : pb::IMessage<CascadingRelationshipDeletes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CascadingRelationshipDeletes> _parser = new pb::MessageParser<CascadingRelationshipDeletes>(() => new CascadingRelationshipDeletes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CascadingRelationshipDeletes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EsriPBuffer.Graph.ApplyEditsResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CascadingRelationshipDeletes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CascadingRelationshipDeletes(CascadingRelationshipDeletes other) : this() {
      relationshipDeleteResults_ = other.relationshipDeleteResults_ != null ? other.relationshipDeleteResults_.Clone() : null;
      originEntityGlobalidArray_ = other.originEntityGlobalidArray_;
      destEntityGlobalidArray_ = other.destEntityGlobalidArray_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CascadingRelationshipDeletes Clone() {
      return new CascadingRelationshipDeletes(this);
    }

    /// <summary>Field number for the "relationship_delete_results" field.</summary>
    public const int RelationshipDeleteResultsFieldNumber = 1;
    private global::EsriPBuffer.Graph.EditResults relationshipDeleteResults_;
    /// <summary>
    /// EditResults for all relationships that are automatically deleted by server because they were connected an entity being deleted
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EsriPBuffer.Graph.EditResults RelationshipDeleteResults {
      get { return relationshipDeleteResults_; }
      set {
        relationshipDeleteResults_ = value;
      }
    }

    /// <summary>Field number for the "origin_entity_globalid_array" field.</summary>
    public const int OriginEntityGlobalidArrayFieldNumber = 2;
    private pb::ByteString originEntityGlobalidArray_ = pb::ByteString.Empty;
    /// <summary>
    /// `origin_entity_globalid_array` is a concatenation of 1..N RFC4122 UUIDs. Size must be multiple of 16.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString OriginEntityGlobalidArray {
      get { return originEntityGlobalidArray_; }
      set {
        originEntityGlobalidArray_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dest_entity_globalid_array" field.</summary>
    public const int DestEntityGlobalidArrayFieldNumber = 3;
    private pb::ByteString destEntityGlobalidArray_ = pb::ByteString.Empty;
    /// <summary>
    /// `dest_entity_globalid_array` is a concatenation of 1..N RFC4122 UUIDs. Size must be multiple of 16.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DestEntityGlobalidArray {
      get { return destEntityGlobalidArray_; }
      set {
        destEntityGlobalidArray_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CascadingRelationshipDeletes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CascadingRelationshipDeletes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RelationshipDeleteResults, other.RelationshipDeleteResults)) return false;
      if (OriginEntityGlobalidArray != other.OriginEntityGlobalidArray) return false;
      if (DestEntityGlobalidArray != other.DestEntityGlobalidArray) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (relationshipDeleteResults_ != null) hash ^= RelationshipDeleteResults.GetHashCode();
      if (OriginEntityGlobalidArray.Length != 0) hash ^= OriginEntityGlobalidArray.GetHashCode();
      if (DestEntityGlobalidArray.Length != 0) hash ^= DestEntityGlobalidArray.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (relationshipDeleteResults_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RelationshipDeleteResults);
      }
      if (OriginEntityGlobalidArray.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(OriginEntityGlobalidArray);
      }
      if (DestEntityGlobalidArray.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(DestEntityGlobalidArray);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (relationshipDeleteResults_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RelationshipDeleteResults);
      }
      if (OriginEntityGlobalidArray.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(OriginEntityGlobalidArray);
      }
      if (DestEntityGlobalidArray.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(DestEntityGlobalidArray);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (relationshipDeleteResults_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RelationshipDeleteResults);
      }
      if (OriginEntityGlobalidArray.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OriginEntityGlobalidArray);
      }
      if (DestEntityGlobalidArray.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DestEntityGlobalidArray);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CascadingRelationshipDeletes other) {
      if (other == null) {
        return;
      }
      if (other.relationshipDeleteResults_ != null) {
        if (relationshipDeleteResults_ == null) {
          RelationshipDeleteResults = new global::EsriPBuffer.Graph.EditResults();
        }
        RelationshipDeleteResults.MergeFrom(other.RelationshipDeleteResults);
      }
      if (other.OriginEntityGlobalidArray.Length != 0) {
        OriginEntityGlobalidArray = other.OriginEntityGlobalidArray;
      }
      if (other.DestEntityGlobalidArray.Length != 0) {
        DestEntityGlobalidArray = other.DestEntityGlobalidArray;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (relationshipDeleteResults_ == null) {
              RelationshipDeleteResults = new global::EsriPBuffer.Graph.EditResults();
            }
            input.ReadMessage(RelationshipDeleteResults);
            break;
          }
          case 18: {
            OriginEntityGlobalidArray = input.ReadBytes();
            break;
          }
          case 26: {
            DestEntityGlobalidArray = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (relationshipDeleteResults_ == null) {
              RelationshipDeleteResults = new global::EsriPBuffer.Graph.EditResults();
            }
            input.ReadMessage(RelationshipDeleteResults);
            break;
          }
          case 18: {
            OriginEntityGlobalidArray = input.ReadBytes();
            break;
          }
          case 26: {
            DestEntityGlobalidArray = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RelationshipTypeSchemaChanges : pb::IMessage<RelationshipTypeSchemaChanges>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RelationshipTypeSchemaChanges> _parser = new pb::MessageParser<RelationshipTypeSchemaChanges>(() => new RelationshipTypeSchemaChanges());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RelationshipTypeSchemaChanges> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EsriPBuffer.Graph.ApplyEditsResponseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RelationshipTypeSchemaChanges() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RelationshipTypeSchemaChanges(RelationshipTypeSchemaChanges other) : this() {
      originEntityTypes_ = other.originEntityTypes_.Clone();
      destEntityTypes_ = other.destEntityTypes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RelationshipTypeSchemaChanges Clone() {
      return new RelationshipTypeSchemaChanges(this);
    }

    /// <summary>Field number for the "origin_entity_types" field.</summary>
    public const int OriginEntityTypesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_originEntityTypes_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> originEntityTypes_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> OriginEntityTypes {
      get { return originEntityTypes_; }
    }

    /// <summary>Field number for the "dest_entity_types" field.</summary>
    public const int DestEntityTypesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_destEntityTypes_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> destEntityTypes_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DestEntityTypes {
      get { return destEntityTypes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RelationshipTypeSchemaChanges);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RelationshipTypeSchemaChanges other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!originEntityTypes_.Equals(other.originEntityTypes_)) return false;
      if(!destEntityTypes_.Equals(other.destEntityTypes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= originEntityTypes_.GetHashCode();
      hash ^= destEntityTypes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      originEntityTypes_.WriteTo(output, _repeated_originEntityTypes_codec);
      destEntityTypes_.WriteTo(output, _repeated_destEntityTypes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      originEntityTypes_.WriteTo(ref output, _repeated_originEntityTypes_codec);
      destEntityTypes_.WriteTo(ref output, _repeated_destEntityTypes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += originEntityTypes_.CalculateSize(_repeated_originEntityTypes_codec);
      size += destEntityTypes_.CalculateSize(_repeated_destEntityTypes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RelationshipTypeSchemaChanges other) {
      if (other == null) {
        return;
      }
      originEntityTypes_.Add(other.originEntityTypes_);
      destEntityTypes_.Add(other.destEntityTypes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            originEntityTypes_.AddEntriesFrom(input, _repeated_originEntityTypes_codec);
            break;
          }
          case 18: {
            destEntityTypes_.AddEntriesFrom(input, _repeated_destEntityTypes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            originEntityTypes_.AddEntriesFrom(ref input, _repeated_originEntityTypes_codec);
            break;
          }
          case 18: {
            destEntityTypes_.AddEntriesFrom(ref input, _repeated_destEntityTypes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GraphApplyEditsResult : pb::IMessage<GraphApplyEditsResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GraphApplyEditsResult> _parser = new pb::MessageParser<GraphApplyEditsResult>(() => new GraphApplyEditsResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GraphApplyEditsResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EsriPBuffer.Graph.ApplyEditsResponseReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GraphApplyEditsResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GraphApplyEditsResult(GraphApplyEditsResult other) : this() {
      error_ = other.error_ != null ? other.error_.Clone() : null;
      entityAddResults_ = other.entityAddResults_.Clone();
      relationshipAddResults_ = other.relationshipAddResults_.Clone();
      entityUpdateResults_ = other.entityUpdateResults_.Clone();
      relationshipUpdateResults_ = other.relationshipUpdateResults_.Clone();
      entityDeleteResults_ = other.entityDeleteResults_.Clone();
      relationshipDeleteResults_ = other.relationshipDeleteResults_.Clone();
      cascadingRelationshipDeleteResults_ = other.cascadingRelationshipDeleteResults_.Clone();
      relTypeSchemaChanges_ = other.relTypeSchemaChanges_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GraphApplyEditsResult Clone() {
      return new GraphApplyEditsResult(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private global::EsriPBuffer.Graph.Error error_;
    /// <summary>
    /// to be used in case there was a non-entity/rel-specific reason for the failure
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EsriPBuffer.Graph.Error Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "entity_add_results" field.</summary>
    public const int EntityAddResultsFieldNumber = 2;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec _map_entityAddResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.EditResults.Parser), 18);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> entityAddResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>();
    /// <summary>
    /// grouped by named object type name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> EntityAddResults {
      get { return entityAddResults_; }
    }

    /// <summary>Field number for the "relationship_add_results" field.</summary>
    public const int RelationshipAddResultsFieldNumber = 3;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec _map_relationshipAddResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.EditResults.Parser), 26);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> relationshipAddResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> RelationshipAddResults {
      get { return relationshipAddResults_; }
    }

    /// <summary>Field number for the "entity_update_results" field.</summary>
    public const int EntityUpdateResultsFieldNumber = 4;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec _map_entityUpdateResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.EditResults.Parser), 34);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> entityUpdateResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>();
    /// <summary>
    /// grouped by named object type name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> EntityUpdateResults {
      get { return entityUpdateResults_; }
    }

    /// <summary>Field number for the "relationship_update_results" field.</summary>
    public const int RelationshipUpdateResultsFieldNumber = 5;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec _map_relationshipUpdateResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.EditResults.Parser), 42);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> relationshipUpdateResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> RelationshipUpdateResults {
      get { return relationshipUpdateResults_; }
    }

    /// <summary>Field number for the "entity_delete_results" field.</summary>
    public const int EntityDeleteResultsFieldNumber = 6;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec _map_entityDeleteResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.EditResults.Parser), 50);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> entityDeleteResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>();
    /// <summary>
    /// grouped by named object type name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> EntityDeleteResults {
      get { return entityDeleteResults_; }
    }

    /// <summary>Field number for the "relationship_delete_results" field.</summary>
    public const int RelationshipDeleteResultsFieldNumber = 7;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec _map_relationshipDeleteResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.EditResults.Parser), 58);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> relationshipDeleteResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.EditResults>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.EditResults> RelationshipDeleteResults {
      get { return relationshipDeleteResults_; }
    }

    /// <summary>Field number for the "cascading_relationship_delete_results" field.</summary>
    public const int CascadingRelationshipDeleteResultsFieldNumber = 8;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.CascadingRelationshipDeletes>.Codec _map_cascadingRelationshipDeleteResults_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.CascadingRelationshipDeletes>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.CascadingRelationshipDeletes.Parser), 66);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.CascadingRelationshipDeletes> cascadingRelationshipDeleteResults_ = new pbc::MapField<string, global::EsriPBuffer.Graph.CascadingRelationshipDeletes>();
    /// <summary>
    /// grouped by relationship type name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.CascadingRelationshipDeletes> CascadingRelationshipDeleteResults {
      get { return cascadingRelationshipDeleteResults_; }
    }

    /// <summary>Field number for the "rel_type_schema_changes" field.</summary>
    public const int RelTypeSchemaChangesFieldNumber = 9;
    private static readonly pbc::MapField<string, global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges>.Codec _map_relTypeSchemaChanges_codec
        = new pbc::MapField<string, global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges.Parser), 74);
    private readonly pbc::MapField<string, global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges> relTypeSchemaChanges_ = new pbc::MapField<string, global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges>();
    /// <summary>
    /// grouped by relationship type name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::EsriPBuffer.Graph.RelationshipTypeSchemaChanges> RelTypeSchemaChanges {
      get { return relTypeSchemaChanges_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GraphApplyEditsResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GraphApplyEditsResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Error, other.Error)) return false;
      if (!EntityAddResults.Equals(other.EntityAddResults)) return false;
      if (!RelationshipAddResults.Equals(other.RelationshipAddResults)) return false;
      if (!EntityUpdateResults.Equals(other.EntityUpdateResults)) return false;
      if (!RelationshipUpdateResults.Equals(other.RelationshipUpdateResults)) return false;
      if (!EntityDeleteResults.Equals(other.EntityDeleteResults)) return false;
      if (!RelationshipDeleteResults.Equals(other.RelationshipDeleteResults)) return false;
      if (!CascadingRelationshipDeleteResults.Equals(other.CascadingRelationshipDeleteResults)) return false;
      if (!RelTypeSchemaChanges.Equals(other.RelTypeSchemaChanges)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (error_ != null) hash ^= Error.GetHashCode();
      hash ^= EntityAddResults.GetHashCode();
      hash ^= RelationshipAddResults.GetHashCode();
      hash ^= EntityUpdateResults.GetHashCode();
      hash ^= RelationshipUpdateResults.GetHashCode();
      hash ^= EntityDeleteResults.GetHashCode();
      hash ^= RelationshipDeleteResults.GetHashCode();
      hash ^= CascadingRelationshipDeleteResults.GetHashCode();
      hash ^= RelTypeSchemaChanges.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (error_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      entityAddResults_.WriteTo(output, _map_entityAddResults_codec);
      relationshipAddResults_.WriteTo(output, _map_relationshipAddResults_codec);
      entityUpdateResults_.WriteTo(output, _map_entityUpdateResults_codec);
      relationshipUpdateResults_.WriteTo(output, _map_relationshipUpdateResults_codec);
      entityDeleteResults_.WriteTo(output, _map_entityDeleteResults_codec);
      relationshipDeleteResults_.WriteTo(output, _map_relationshipDeleteResults_codec);
      cascadingRelationshipDeleteResults_.WriteTo(output, _map_cascadingRelationshipDeleteResults_codec);
      relTypeSchemaChanges_.WriteTo(output, _map_relTypeSchemaChanges_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (error_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      entityAddResults_.WriteTo(ref output, _map_entityAddResults_codec);
      relationshipAddResults_.WriteTo(ref output, _map_relationshipAddResults_codec);
      entityUpdateResults_.WriteTo(ref output, _map_entityUpdateResults_codec);
      relationshipUpdateResults_.WriteTo(ref output, _map_relationshipUpdateResults_codec);
      entityDeleteResults_.WriteTo(ref output, _map_entityDeleteResults_codec);
      relationshipDeleteResults_.WriteTo(ref output, _map_relationshipDeleteResults_codec);
      cascadingRelationshipDeleteResults_.WriteTo(ref output, _map_cascadingRelationshipDeleteResults_codec);
      relTypeSchemaChanges_.WriteTo(ref output, _map_relTypeSchemaChanges_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (error_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      size += entityAddResults_.CalculateSize(_map_entityAddResults_codec);
      size += relationshipAddResults_.CalculateSize(_map_relationshipAddResults_codec);
      size += entityUpdateResults_.CalculateSize(_map_entityUpdateResults_codec);
      size += relationshipUpdateResults_.CalculateSize(_map_relationshipUpdateResults_codec);
      size += entityDeleteResults_.CalculateSize(_map_entityDeleteResults_codec);
      size += relationshipDeleteResults_.CalculateSize(_map_relationshipDeleteResults_codec);
      size += cascadingRelationshipDeleteResults_.CalculateSize(_map_cascadingRelationshipDeleteResults_codec);
      size += relTypeSchemaChanges_.CalculateSize(_map_relTypeSchemaChanges_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GraphApplyEditsResult other) {
      if (other == null) {
        return;
      }
      if (other.error_ != null) {
        if (error_ == null) {
          Error = new global::EsriPBuffer.Graph.Error();
        }
        Error.MergeFrom(other.Error);
      }
      entityAddResults_.Add(other.entityAddResults_);
      relationshipAddResults_.Add(other.relationshipAddResults_);
      entityUpdateResults_.Add(other.entityUpdateResults_);
      relationshipUpdateResults_.Add(other.relationshipUpdateResults_);
      entityDeleteResults_.Add(other.entityDeleteResults_);
      relationshipDeleteResults_.Add(other.relationshipDeleteResults_);
      cascadingRelationshipDeleteResults_.Add(other.cascadingRelationshipDeleteResults_);
      relTypeSchemaChanges_.Add(other.relTypeSchemaChanges_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (error_ == null) {
              Error = new global::EsriPBuffer.Graph.Error();
            }
            input.ReadMessage(Error);
            break;
          }
          case 18: {
            entityAddResults_.AddEntriesFrom(input, _map_entityAddResults_codec);
            break;
          }
          case 26: {
            relationshipAddResults_.AddEntriesFrom(input, _map_relationshipAddResults_codec);
            break;
          }
          case 34: {
            entityUpdateResults_.AddEntriesFrom(input, _map_entityUpdateResults_codec);
            break;
          }
          case 42: {
            relationshipUpdateResults_.AddEntriesFrom(input, _map_relationshipUpdateResults_codec);
            break;
          }
          case 50: {
            entityDeleteResults_.AddEntriesFrom(input, _map_entityDeleteResults_codec);
            break;
          }
          case 58: {
            relationshipDeleteResults_.AddEntriesFrom(input, _map_relationshipDeleteResults_codec);
            break;
          }
          case 66: {
            cascadingRelationshipDeleteResults_.AddEntriesFrom(input, _map_cascadingRelationshipDeleteResults_codec);
            break;
          }
          case 74: {
            relTypeSchemaChanges_.AddEntriesFrom(input, _map_relTypeSchemaChanges_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (error_ == null) {
              Error = new global::EsriPBuffer.Graph.Error();
            }
            input.ReadMessage(Error);
            break;
          }
          case 18: {
            entityAddResults_.AddEntriesFrom(ref input, _map_entityAddResults_codec);
            break;
          }
          case 26: {
            relationshipAddResults_.AddEntriesFrom(ref input, _map_relationshipAddResults_codec);
            break;
          }
          case 34: {
            entityUpdateResults_.AddEntriesFrom(ref input, _map_entityUpdateResults_codec);
            break;
          }
          case 42: {
            relationshipUpdateResults_.AddEntriesFrom(ref input, _map_relationshipUpdateResults_codec);
            break;
          }
          case 50: {
            entityDeleteResults_.AddEntriesFrom(ref input, _map_entityDeleteResults_codec);
            break;
          }
          case 58: {
            relationshipDeleteResults_.AddEntriesFrom(ref input, _map_relationshipDeleteResults_codec);
            break;
          }
          case 66: {
            cascadingRelationshipDeleteResults_.AddEntriesFrom(ref input, _map_cascadingRelationshipDeleteResults_codec);
            break;
          }
          case 74: {
            relTypeSchemaChanges_.AddEntriesFrom(ref input, _map_relTypeSchemaChanges_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
