// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: esriPBuffer/graph/QueryDataModelResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EsriPBuffer.Graph {

  /// <summary>Holder for reflection information generated from esriPBuffer/graph/QueryDataModelResponse.proto</summary>
  public static partial class QueryDataModelResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for esriPBuffer/graph/QueryDataModelResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryDataModelResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5lc3JpUEJ1ZmZlci9ncmFwaC9RdWVyeURhdGFNb2RlbFJlc3BvbnNlLnBy",
            "b3RvEhFlc3JpUEJ1ZmZlci5ncmFwaBobZXNyaVBCdWZmZXIvRXNyaVR5cGVz",
            "LnByb3RvGiZlc3JpUEJ1ZmZlci9ncmFwaC9EYXRhTW9kZWxUeXBlcy5wcm90",
            "byL8AwoOR3JhcGhEYXRhTW9kZWwSHAoUZGF0YV9tb2RlbF90aW1lc3RhbXAY",
            "ASABKAQSQgoRc3BhdGlhbF9yZWZlcmVuY2UYAiABKAsyJy5lc3JpUEJ1ZmZl",
            "ci5Fc3JpVHlwZXMuU3BhdGlhbFJlZmVyZW5jZRIuCgdkb21haW5zGAMgAygL",
            "Mh0uZXNyaVBCdWZmZXIuRXNyaVR5cGVzLkRvbWFpbhIzCgxlbnRpdHlfdHlw",
            "ZXMYBCADKAsyHS5lc3JpUEJ1ZmZlci5ncmFwaC5FbnRpdHlUeXBlEj8KEnJl",
            "bGF0aW9uc2hpcF90eXBlcxgFIAMoCzIjLmVzcmlQQnVmZmVyLmdyYXBoLlJl",
            "bGF0aW9uc2hpcFR5cGUSDgoGc3RyaWN0GAYgASgIEhkKEW9iamVjdGlkX3By",
            "b3BlcnR5GAcgASgJEhkKEWdsb2JhbGlkX3Byb3BlcnR5GAggASgJEicKH29y",
            "aWdpbl9lbnRpdHlfZ2xvYmFsaWRfcHJvcGVydHkYCSABKAkSJQodZGVzdF9l",
            "bnRpdHlfZ2xvYmFsaWRfcHJvcGVydHkYCiABKAkSTAoUZG9jX2VudGl0eV90",
            "eXBlX2luZm8YCyABKAsyLi5lc3JpUEJ1ZmZlci5ncmFwaC5HcmFwaERvY3Vt",
            "ZW50RW50aXR5VHlwZUluZm9CJQoeY29tLmVzcmkuYXJjZ2lzLnByb3RvYnVm",
            "LmdyYXBoSAP4AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EsriPBuffer.EsriTypesReflection.Descriptor, global::EsriPBuffer.Graph.DataModelTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EsriPBuffer.Graph.GraphDataModel), global::EsriPBuffer.Graph.GraphDataModel.Parser, new[]{ "DataModelTimestamp", "SpatialReference", "Domains", "EntityTypes", "RelationshipTypes", "Strict", "ObjectidProperty", "GlobalidProperty", "OriginEntityGlobalidProperty", "DestEntityGlobalidProperty", "DocEntityTypeInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GraphDataModel : pb::IMessage<GraphDataModel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GraphDataModel> _parser = new pb::MessageParser<GraphDataModel>(() => new GraphDataModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GraphDataModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EsriPBuffer.Graph.QueryDataModelResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GraphDataModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GraphDataModel(GraphDataModel other) : this() {
      dataModelTimestamp_ = other.dataModelTimestamp_;
      spatialReference_ = other.spatialReference_ != null ? other.spatialReference_.Clone() : null;
      domains_ = other.domains_.Clone();
      entityTypes_ = other.entityTypes_.Clone();
      relationshipTypes_ = other.relationshipTypes_.Clone();
      strict_ = other.strict_;
      objectidProperty_ = other.objectidProperty_;
      globalidProperty_ = other.globalidProperty_;
      originEntityGlobalidProperty_ = other.originEntityGlobalidProperty_;
      destEntityGlobalidProperty_ = other.destEntityGlobalidProperty_;
      docEntityTypeInfo_ = other.docEntityTypeInfo_ != null ? other.docEntityTypeInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GraphDataModel Clone() {
      return new GraphDataModel(this);
    }

    /// <summary>Field number for the "data_model_timestamp" field.</summary>
    public const int DataModelTimestampFieldNumber = 1;
    private ulong dataModelTimestamp_;
    /// <summary>
    /// UTC UNIX epoch in milliseconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong DataModelTimestamp {
      get { return dataModelTimestamp_; }
      set {
        dataModelTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "spatial_reference" field.</summary>
    public const int SpatialReferenceFieldNumber = 2;
    private global::EsriPBuffer.EsriTypes.Types.SpatialReference spatialReference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EsriPBuffer.EsriTypes.Types.SpatialReference SpatialReference {
      get { return spatialReference_; }
      set {
        spatialReference_ = value;
      }
    }

    /// <summary>Field number for the "domains" field.</summary>
    public const int DomainsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::EsriPBuffer.EsriTypes.Types.Domain> _repeated_domains_codec
        = pb::FieldCodec.ForMessage(26, global::EsriPBuffer.EsriTypes.Types.Domain.Parser);
    private readonly pbc::RepeatedField<global::EsriPBuffer.EsriTypes.Types.Domain> domains_ = new pbc::RepeatedField<global::EsriPBuffer.EsriTypes.Types.Domain>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EsriPBuffer.EsriTypes.Types.Domain> Domains {
      get { return domains_; }
    }

    /// <summary>Field number for the "entity_types" field.</summary>
    public const int EntityTypesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::EsriPBuffer.Graph.EntityType> _repeated_entityTypes_codec
        = pb::FieldCodec.ForMessage(34, global::EsriPBuffer.Graph.EntityType.Parser);
    private readonly pbc::RepeatedField<global::EsriPBuffer.Graph.EntityType> entityTypes_ = new pbc::RepeatedField<global::EsriPBuffer.Graph.EntityType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EsriPBuffer.Graph.EntityType> EntityTypes {
      get { return entityTypes_; }
    }

    /// <summary>Field number for the "relationship_types" field.</summary>
    public const int RelationshipTypesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EsriPBuffer.Graph.RelationshipType> _repeated_relationshipTypes_codec
        = pb::FieldCodec.ForMessage(42, global::EsriPBuffer.Graph.RelationshipType.Parser);
    private readonly pbc::RepeatedField<global::EsriPBuffer.Graph.RelationshipType> relationshipTypes_ = new pbc::RepeatedField<global::EsriPBuffer.Graph.RelationshipType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EsriPBuffer.Graph.RelationshipType> RelationshipTypes {
      get { return relationshipTypes_; }
    }

    /// <summary>Field number for the "strict" field.</summary>
    public const int StrictFieldNumber = 6;
    private bool strict_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Strict {
      get { return strict_; }
      set {
        strict_ = value;
      }
    }

    /// <summary>Field number for the "objectid_property" field.</summary>
    public const int ObjectidPropertyFieldNumber = 7;
    private string objectidProperty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ObjectidProperty {
      get { return objectidProperty_; }
      set {
        objectidProperty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "globalid_property" field.</summary>
    public const int GlobalidPropertyFieldNumber = 8;
    private string globalidProperty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GlobalidProperty {
      get { return globalidProperty_; }
      set {
        globalidProperty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "origin_entity_globalid_property" field.</summary>
    public const int OriginEntityGlobalidPropertyFieldNumber = 9;
    private string originEntityGlobalidProperty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OriginEntityGlobalidProperty {
      get { return originEntityGlobalidProperty_; }
      set {
        originEntityGlobalidProperty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dest_entity_globalid_property" field.</summary>
    public const int DestEntityGlobalidPropertyFieldNumber = 10;
    private string destEntityGlobalidProperty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DestEntityGlobalidProperty {
      get { return destEntityGlobalidProperty_; }
      set {
        destEntityGlobalidProperty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "doc_entity_type_info" field.</summary>
    public const int DocEntityTypeInfoFieldNumber = 11;
    private global::EsriPBuffer.Graph.GraphDocumentEntityTypeInfo docEntityTypeInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EsriPBuffer.Graph.GraphDocumentEntityTypeInfo DocEntityTypeInfo {
      get { return docEntityTypeInfo_; }
      set {
        docEntityTypeInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GraphDataModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GraphDataModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DataModelTimestamp != other.DataModelTimestamp) return false;
      if (!object.Equals(SpatialReference, other.SpatialReference)) return false;
      if(!domains_.Equals(other.domains_)) return false;
      if(!entityTypes_.Equals(other.entityTypes_)) return false;
      if(!relationshipTypes_.Equals(other.relationshipTypes_)) return false;
      if (Strict != other.Strict) return false;
      if (ObjectidProperty != other.ObjectidProperty) return false;
      if (GlobalidProperty != other.GlobalidProperty) return false;
      if (OriginEntityGlobalidProperty != other.OriginEntityGlobalidProperty) return false;
      if (DestEntityGlobalidProperty != other.DestEntityGlobalidProperty) return false;
      if (!object.Equals(DocEntityTypeInfo, other.DocEntityTypeInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DataModelTimestamp != 0UL) hash ^= DataModelTimestamp.GetHashCode();
      if (spatialReference_ != null) hash ^= SpatialReference.GetHashCode();
      hash ^= domains_.GetHashCode();
      hash ^= entityTypes_.GetHashCode();
      hash ^= relationshipTypes_.GetHashCode();
      if (Strict != false) hash ^= Strict.GetHashCode();
      if (ObjectidProperty.Length != 0) hash ^= ObjectidProperty.GetHashCode();
      if (GlobalidProperty.Length != 0) hash ^= GlobalidProperty.GetHashCode();
      if (OriginEntityGlobalidProperty.Length != 0) hash ^= OriginEntityGlobalidProperty.GetHashCode();
      if (DestEntityGlobalidProperty.Length != 0) hash ^= DestEntityGlobalidProperty.GetHashCode();
      if (docEntityTypeInfo_ != null) hash ^= DocEntityTypeInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DataModelTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(DataModelTimestamp);
      }
      if (spatialReference_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpatialReference);
      }
      domains_.WriteTo(output, _repeated_domains_codec);
      entityTypes_.WriteTo(output, _repeated_entityTypes_codec);
      relationshipTypes_.WriteTo(output, _repeated_relationshipTypes_codec);
      if (Strict != false) {
        output.WriteRawTag(48);
        output.WriteBool(Strict);
      }
      if (ObjectidProperty.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ObjectidProperty);
      }
      if (GlobalidProperty.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(GlobalidProperty);
      }
      if (OriginEntityGlobalidProperty.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(OriginEntityGlobalidProperty);
      }
      if (DestEntityGlobalidProperty.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DestEntityGlobalidProperty);
      }
      if (docEntityTypeInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DocEntityTypeInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DataModelTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(DataModelTimestamp);
      }
      if (spatialReference_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpatialReference);
      }
      domains_.WriteTo(ref output, _repeated_domains_codec);
      entityTypes_.WriteTo(ref output, _repeated_entityTypes_codec);
      relationshipTypes_.WriteTo(ref output, _repeated_relationshipTypes_codec);
      if (Strict != false) {
        output.WriteRawTag(48);
        output.WriteBool(Strict);
      }
      if (ObjectidProperty.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ObjectidProperty);
      }
      if (GlobalidProperty.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(GlobalidProperty);
      }
      if (OriginEntityGlobalidProperty.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(OriginEntityGlobalidProperty);
      }
      if (DestEntityGlobalidProperty.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DestEntityGlobalidProperty);
      }
      if (docEntityTypeInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DocEntityTypeInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DataModelTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DataModelTimestamp);
      }
      if (spatialReference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpatialReference);
      }
      size += domains_.CalculateSize(_repeated_domains_codec);
      size += entityTypes_.CalculateSize(_repeated_entityTypes_codec);
      size += relationshipTypes_.CalculateSize(_repeated_relationshipTypes_codec);
      if (Strict != false) {
        size += 1 + 1;
      }
      if (ObjectidProperty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObjectidProperty);
      }
      if (GlobalidProperty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GlobalidProperty);
      }
      if (OriginEntityGlobalidProperty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginEntityGlobalidProperty);
      }
      if (DestEntityGlobalidProperty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DestEntityGlobalidProperty);
      }
      if (docEntityTypeInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DocEntityTypeInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GraphDataModel other) {
      if (other == null) {
        return;
      }
      if (other.DataModelTimestamp != 0UL) {
        DataModelTimestamp = other.DataModelTimestamp;
      }
      if (other.spatialReference_ != null) {
        if (spatialReference_ == null) {
          SpatialReference = new global::EsriPBuffer.EsriTypes.Types.SpatialReference();
        }
        SpatialReference.MergeFrom(other.SpatialReference);
      }
      domains_.Add(other.domains_);
      entityTypes_.Add(other.entityTypes_);
      relationshipTypes_.Add(other.relationshipTypes_);
      if (other.Strict != false) {
        Strict = other.Strict;
      }
      if (other.ObjectidProperty.Length != 0) {
        ObjectidProperty = other.ObjectidProperty;
      }
      if (other.GlobalidProperty.Length != 0) {
        GlobalidProperty = other.GlobalidProperty;
      }
      if (other.OriginEntityGlobalidProperty.Length != 0) {
        OriginEntityGlobalidProperty = other.OriginEntityGlobalidProperty;
      }
      if (other.DestEntityGlobalidProperty.Length != 0) {
        DestEntityGlobalidProperty = other.DestEntityGlobalidProperty;
      }
      if (other.docEntityTypeInfo_ != null) {
        if (docEntityTypeInfo_ == null) {
          DocEntityTypeInfo = new global::EsriPBuffer.Graph.GraphDocumentEntityTypeInfo();
        }
        DocEntityTypeInfo.MergeFrom(other.DocEntityTypeInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DataModelTimestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            if (spatialReference_ == null) {
              SpatialReference = new global::EsriPBuffer.EsriTypes.Types.SpatialReference();
            }
            input.ReadMessage(SpatialReference);
            break;
          }
          case 26: {
            domains_.AddEntriesFrom(input, _repeated_domains_codec);
            break;
          }
          case 34: {
            entityTypes_.AddEntriesFrom(input, _repeated_entityTypes_codec);
            break;
          }
          case 42: {
            relationshipTypes_.AddEntriesFrom(input, _repeated_relationshipTypes_codec);
            break;
          }
          case 48: {
            Strict = input.ReadBool();
            break;
          }
          case 58: {
            ObjectidProperty = input.ReadString();
            break;
          }
          case 66: {
            GlobalidProperty = input.ReadString();
            break;
          }
          case 74: {
            OriginEntityGlobalidProperty = input.ReadString();
            break;
          }
          case 82: {
            DestEntityGlobalidProperty = input.ReadString();
            break;
          }
          case 90: {
            if (docEntityTypeInfo_ == null) {
              DocEntityTypeInfo = new global::EsriPBuffer.Graph.GraphDocumentEntityTypeInfo();
            }
            input.ReadMessage(DocEntityTypeInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DataModelTimestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            if (spatialReference_ == null) {
              SpatialReference = new global::EsriPBuffer.EsriTypes.Types.SpatialReference();
            }
            input.ReadMessage(SpatialReference);
            break;
          }
          case 26: {
            domains_.AddEntriesFrom(ref input, _repeated_domains_codec);
            break;
          }
          case 34: {
            entityTypes_.AddEntriesFrom(ref input, _repeated_entityTypes_codec);
            break;
          }
          case 42: {
            relationshipTypes_.AddEntriesFrom(ref input, _repeated_relationshipTypes_codec);
            break;
          }
          case 48: {
            Strict = input.ReadBool();
            break;
          }
          case 58: {
            ObjectidProperty = input.ReadString();
            break;
          }
          case 66: {
            GlobalidProperty = input.ReadString();
            break;
          }
          case 74: {
            OriginEntityGlobalidProperty = input.ReadString();
            break;
          }
          case 82: {
            DestEntityGlobalidProperty = input.ReadString();
            break;
          }
          case 90: {
            if (docEntityTypeInfo_ == null) {
              DocEntityTypeInfo = new global::EsriPBuffer.Graph.GraphDocumentEntityTypeInfo();
            }
            input.ReadMessage(DocEntityTypeInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
