// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: esriPBuffer/graph/DeleteIndexesResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "esriPBuffer/graph/EsriGraphTypes.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace esriPBuffer {
namespace graph {
class GraphIndexDeleteResponse;
class GraphIndexDeleteResponseDefaultTypeInternal;
extern GraphIndexDeleteResponseDefaultTypeInternal _GraphIndexDeleteResponse_default_instance_;
class GraphIndexDeleteResult;
class GraphIndexDeleteResultDefaultTypeInternal;
extern GraphIndexDeleteResultDefaultTypeInternal _GraphIndexDeleteResult_default_instance_;
}  // namespace graph
}  // namespace esriPBuffer
PROTOBUF_NAMESPACE_OPEN
template<> ::esriPBuffer::graph::GraphIndexDeleteResponse* Arena::CreateMaybeMessage<::esriPBuffer::graph::GraphIndexDeleteResponse>(Arena*);
template<> ::esriPBuffer::graph::GraphIndexDeleteResult* Arena::CreateMaybeMessage<::esriPBuffer::graph::GraphIndexDeleteResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace esriPBuffer {
namespace graph {

// ===================================================================

class GraphIndexDeleteResult PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:esriPBuffer.graph.GraphIndexDeleteResult) */ {
 public:
  inline GraphIndexDeleteResult() : GraphIndexDeleteResult(nullptr) {}
  virtual ~GraphIndexDeleteResult();

  GraphIndexDeleteResult(const GraphIndexDeleteResult& from);
  GraphIndexDeleteResult(GraphIndexDeleteResult&& from) noexcept
    : GraphIndexDeleteResult() {
    *this = ::std::move(from);
  }

  inline GraphIndexDeleteResult& operator=(const GraphIndexDeleteResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphIndexDeleteResult& operator=(GraphIndexDeleteResult&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GraphIndexDeleteResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphIndexDeleteResult* internal_default_instance() {
    return reinterpret_cast<const GraphIndexDeleteResult*>(
               &_GraphIndexDeleteResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GraphIndexDeleteResult& a, GraphIndexDeleteResult& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphIndexDeleteResult* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphIndexDeleteResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphIndexDeleteResult* New() const final {
    return CreateMaybeMessage<GraphIndexDeleteResult>(nullptr);
  }

  GraphIndexDeleteResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphIndexDeleteResult>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const GraphIndexDeleteResult& from);
  void MergeFrom(const GraphIndexDeleteResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GraphIndexDeleteResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esriPBuffer.graph.GraphIndexDeleteResult";
  }
  protected:
  explicit GraphIndexDeleteResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .esriPBuffer.graph.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::esriPBuffer::graph::Error& error() const;
  ::esriPBuffer::graph::Error* release_error();
  ::esriPBuffer::graph::Error* mutable_error();
  void set_allocated_error(::esriPBuffer::graph::Error* error);
  private:
  const ::esriPBuffer::graph::Error& _internal_error() const;
  ::esriPBuffer::graph::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::esriPBuffer::graph::Error* error);
  ::esriPBuffer::graph::Error* unsafe_arena_release_error();

  // @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphIndexDeleteResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::esriPBuffer::graph::Error* error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto;
};
// -------------------------------------------------------------------

class GraphIndexDeleteResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:esriPBuffer.graph.GraphIndexDeleteResponse) */ {
 public:
  inline GraphIndexDeleteResponse() : GraphIndexDeleteResponse(nullptr) {}
  virtual ~GraphIndexDeleteResponse();

  GraphIndexDeleteResponse(const GraphIndexDeleteResponse& from);
  GraphIndexDeleteResponse(GraphIndexDeleteResponse&& from) noexcept
    : GraphIndexDeleteResponse() {
    *this = ::std::move(from);
  }

  inline GraphIndexDeleteResponse& operator=(const GraphIndexDeleteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphIndexDeleteResponse& operator=(GraphIndexDeleteResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GraphIndexDeleteResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphIndexDeleteResponse* internal_default_instance() {
    return reinterpret_cast<const GraphIndexDeleteResponse*>(
               &_GraphIndexDeleteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GraphIndexDeleteResponse& a, GraphIndexDeleteResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphIndexDeleteResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphIndexDeleteResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphIndexDeleteResponse* New() const final {
    return CreateMaybeMessage<GraphIndexDeleteResponse>(nullptr);
  }

  GraphIndexDeleteResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphIndexDeleteResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const GraphIndexDeleteResponse& from);
  void MergeFrom(const GraphIndexDeleteResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GraphIndexDeleteResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esriPBuffer.graph.GraphIndexDeleteResponse";
  }
  protected:
  explicit GraphIndexDeleteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexDeleteResultsFieldNumber = 2,
    kErrorFieldNumber = 1,
  };
  // repeated .esriPBuffer.graph.GraphIndexDeleteResult index_delete_results = 2;
  int index_delete_results_size() const;
  private:
  int _internal_index_delete_results_size() const;
  public:
  void clear_index_delete_results();
  ::esriPBuffer::graph::GraphIndexDeleteResult* mutable_index_delete_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphIndexDeleteResult >*
      mutable_index_delete_results();
  private:
  const ::esriPBuffer::graph::GraphIndexDeleteResult& _internal_index_delete_results(int index) const;
  ::esriPBuffer::graph::GraphIndexDeleteResult* _internal_add_index_delete_results();
  public:
  const ::esriPBuffer::graph::GraphIndexDeleteResult& index_delete_results(int index) const;
  ::esriPBuffer::graph::GraphIndexDeleteResult* add_index_delete_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphIndexDeleteResult >&
      index_delete_results() const;

  // .esriPBuffer.graph.Error error = 1;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::esriPBuffer::graph::Error& error() const;
  ::esriPBuffer::graph::Error* release_error();
  ::esriPBuffer::graph::Error* mutable_error();
  void set_allocated_error(::esriPBuffer::graph::Error* error);
  private:
  const ::esriPBuffer::graph::Error& _internal_error() const;
  ::esriPBuffer::graph::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::esriPBuffer::graph::Error* error);
  ::esriPBuffer::graph::Error* unsafe_arena_release_error();

  // @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphIndexDeleteResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphIndexDeleteResult > index_delete_results_;
  ::esriPBuffer::graph::Error* error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraphIndexDeleteResult

// string name = 1;
inline void GraphIndexDeleteResult::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GraphIndexDeleteResult::name() const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphIndexDeleteResult.name)
  return _internal_name();
}
inline void GraphIndexDeleteResult::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:esriPBuffer.graph.GraphIndexDeleteResult.name)
}
inline std::string* GraphIndexDeleteResult::mutable_name() {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphIndexDeleteResult.name)
  return _internal_mutable_name();
}
inline const std::string& GraphIndexDeleteResult::_internal_name() const {
  return name_.Get();
}
inline void GraphIndexDeleteResult::_internal_set_name(const std::string& value) {
  
  name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GraphIndexDeleteResult::set_name(std::string&& value) {
  
  name_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:esriPBuffer.graph.GraphIndexDeleteResult.name)
}
inline void GraphIndexDeleteResult::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:esriPBuffer.graph.GraphIndexDeleteResult.name)
}
inline void GraphIndexDeleteResult::set_name(const char* value,
    size_t size) {
  
  name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:esriPBuffer.graph.GraphIndexDeleteResult.name)
}
inline std::string* GraphIndexDeleteResult::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GraphIndexDeleteResult::release_name() {
  // @@protoc_insertion_point(field_release:esriPBuffer.graph.GraphIndexDeleteResult.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraphIndexDeleteResult::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:esriPBuffer.graph.GraphIndexDeleteResult.name)
}

// .esriPBuffer.graph.Error error = 2;
inline bool GraphIndexDeleteResult::_internal_has_error() const {
  return this != internal_default_instance() && error_ != nullptr;
}
inline bool GraphIndexDeleteResult::has_error() const {
  return _internal_has_error();
}
inline const ::esriPBuffer::graph::Error& GraphIndexDeleteResult::_internal_error() const {
  const ::esriPBuffer::graph::Error* p = error_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esriPBuffer::graph::Error*>(
      &::esriPBuffer::graph::_Error_default_instance_);
}
inline const ::esriPBuffer::graph::Error& GraphIndexDeleteResult::error() const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphIndexDeleteResult.error)
  return _internal_error();
}
inline void GraphIndexDeleteResult::unsafe_arena_set_allocated_error(
    ::esriPBuffer::graph::Error* error) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  error_ = error;
  if (error) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esriPBuffer.graph.GraphIndexDeleteResult.error)
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResult::release_error() {
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResult::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:esriPBuffer.graph.GraphIndexDeleteResult.error)
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResult::_internal_mutable_error() {
  
  if (error_ == nullptr) {
    auto* p = CreateMaybeMessage<::esriPBuffer::graph::Error>(GetArena());
    error_ = p;
  }
  return error_;
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResult::mutable_error() {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphIndexDeleteResult.error)
  return _internal_mutable_error();
}
inline void GraphIndexDeleteResult::set_allocated_error(::esriPBuffer::graph::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error)->GetArena();
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:esriPBuffer.graph.GraphIndexDeleteResult.error)
}

// -------------------------------------------------------------------

// GraphIndexDeleteResponse

// .esriPBuffer.graph.Error error = 1;
inline bool GraphIndexDeleteResponse::_internal_has_error() const {
  return this != internal_default_instance() && error_ != nullptr;
}
inline bool GraphIndexDeleteResponse::has_error() const {
  return _internal_has_error();
}
inline const ::esriPBuffer::graph::Error& GraphIndexDeleteResponse::_internal_error() const {
  const ::esriPBuffer::graph::Error* p = error_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esriPBuffer::graph::Error*>(
      &::esriPBuffer::graph::_Error_default_instance_);
}
inline const ::esriPBuffer::graph::Error& GraphIndexDeleteResponse::error() const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphIndexDeleteResponse.error)
  return _internal_error();
}
inline void GraphIndexDeleteResponse::unsafe_arena_set_allocated_error(
    ::esriPBuffer::graph::Error* error) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  error_ = error;
  if (error) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esriPBuffer.graph.GraphIndexDeleteResponse.error)
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResponse::release_error() {
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResponse::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:esriPBuffer.graph.GraphIndexDeleteResponse.error)
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResponse::_internal_mutable_error() {
  
  if (error_ == nullptr) {
    auto* p = CreateMaybeMessage<::esriPBuffer::graph::Error>(GetArena());
    error_ = p;
  }
  return error_;
}
inline ::esriPBuffer::graph::Error* GraphIndexDeleteResponse::mutable_error() {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphIndexDeleteResponse.error)
  return _internal_mutable_error();
}
inline void GraphIndexDeleteResponse::set_allocated_error(::esriPBuffer::graph::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error)->GetArena();
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:esriPBuffer.graph.GraphIndexDeleteResponse.error)
}

// repeated .esriPBuffer.graph.GraphIndexDeleteResult index_delete_results = 2;
inline int GraphIndexDeleteResponse::_internal_index_delete_results_size() const {
  return index_delete_results_.size();
}
inline int GraphIndexDeleteResponse::index_delete_results_size() const {
  return _internal_index_delete_results_size();
}
inline void GraphIndexDeleteResponse::clear_index_delete_results() {
  index_delete_results_.Clear();
}
inline ::esriPBuffer::graph::GraphIndexDeleteResult* GraphIndexDeleteResponse::mutable_index_delete_results(int index) {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphIndexDeleteResponse.index_delete_results)
  return index_delete_results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphIndexDeleteResult >*
GraphIndexDeleteResponse::mutable_index_delete_results() {
  // @@protoc_insertion_point(field_mutable_list:esriPBuffer.graph.GraphIndexDeleteResponse.index_delete_results)
  return &index_delete_results_;
}
inline const ::esriPBuffer::graph::GraphIndexDeleteResult& GraphIndexDeleteResponse::_internal_index_delete_results(int index) const {
  return index_delete_results_.Get(index);
}
inline const ::esriPBuffer::graph::GraphIndexDeleteResult& GraphIndexDeleteResponse::index_delete_results(int index) const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphIndexDeleteResponse.index_delete_results)
  return _internal_index_delete_results(index);
}
inline ::esriPBuffer::graph::GraphIndexDeleteResult* GraphIndexDeleteResponse::_internal_add_index_delete_results() {
  return index_delete_results_.Add();
}
inline ::esriPBuffer::graph::GraphIndexDeleteResult* GraphIndexDeleteResponse::add_index_delete_results() {
  // @@protoc_insertion_point(field_add:esriPBuffer.graph.GraphIndexDeleteResponse.index_delete_results)
  return _internal_add_index_delete_results();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphIndexDeleteResult >&
GraphIndexDeleteResponse::index_delete_results() const {
  // @@protoc_insertion_point(field_list:esriPBuffer.graph.GraphIndexDeleteResponse.index_delete_results)
  return index_delete_results_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace graph
}  // namespace esriPBuffer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_esriPBuffer_2fgraph_2fDeleteIndexesResponse_2eproto
