// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: esriPBuffer/graph/AddDomainRequest.proto

#include "esriPBuffer/graph/AddDomainRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_esriPBuffer_2fEsriTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_EsriTypes_Domain_esriPBuffer_2fEsriTypes_2eproto;
namespace esriPBuffer {
namespace graph {
class GraphDomainAddRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GraphDomainAddRequest> _instance;
} _GraphDomainAddRequest_default_instance_;
}  // namespace graph
}  // namespace esriPBuffer
static void InitDefaultsscc_info_GraphDomainAddRequest_esriPBuffer_2fgraph_2fAddDomainRequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::esriPBuffer::graph::_GraphDomainAddRequest_default_instance_;
    new (ptr) ::esriPBuffer::graph::GraphDomainAddRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::esriPBuffer::graph::GraphDomainAddRequest::InitAsDefaultInstance();
}

EXT_CLASS ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GraphDomainAddRequest_esriPBuffer_2fgraph_2fAddDomainRequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GraphDomainAddRequest_esriPBuffer_2fgraph_2fAddDomainRequest_2eproto}, {
      &scc_info_EsriTypes_Domain_esriPBuffer_2fEsriTypes_2eproto.base,}};

namespace esriPBuffer {
namespace graph {

// ===================================================================

void GraphDomainAddRequest::InitAsDefaultInstance() {
  ::esriPBuffer::graph::_GraphDomainAddRequest_default_instance_._instance.get_mutable()->domains_ = const_cast< ::esriPBuffer::EsriTypes_Domain*>(
      ::esriPBuffer::EsriTypes_Domain::internal_default_instance());
}
class GraphDomainAddRequest::_Internal {
 public:
  static const ::esriPBuffer::EsriTypes_Domain& domains(const GraphDomainAddRequest* msg);
};

const ::esriPBuffer::EsriTypes_Domain&
GraphDomainAddRequest::_Internal::domains(const GraphDomainAddRequest* msg) {
  return *msg->domains_;
}
void GraphDomainAddRequest::clear_domains() {
  if (GetArena() == nullptr && domains_ != nullptr) {
    delete domains_;
  }
  domains_ = nullptr;
}
GraphDomainAddRequest::GraphDomainAddRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:esriPBuffer.graph.GraphDomainAddRequest)
}
GraphDomainAddRequest::GraphDomainAddRequest(const GraphDomainAddRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_domains()) {
    domains_ = new ::esriPBuffer::EsriTypes_Domain(*from.domains_);
  } else {
    domains_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:esriPBuffer.graph.GraphDomainAddRequest)
}

void GraphDomainAddRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GraphDomainAddRequest_esriPBuffer_2fgraph_2fAddDomainRequest_2eproto.base);
  domains_ = nullptr;
}

GraphDomainAddRequest::~GraphDomainAddRequest() {
  // @@protoc_insertion_point(destructor:esriPBuffer.graph.GraphDomainAddRequest)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void GraphDomainAddRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete domains_;
}

void GraphDomainAddRequest::ArenaDtor(void* object) {
  GraphDomainAddRequest* _this = reinterpret_cast< GraphDomainAddRequest* >(object);
  (void)_this;
}
void GraphDomainAddRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GraphDomainAddRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GraphDomainAddRequest& GraphDomainAddRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GraphDomainAddRequest_esriPBuffer_2fgraph_2fAddDomainRequest_2eproto.base);
  return *internal_default_instance();
}


void GraphDomainAddRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:esriPBuffer.graph.GraphDomainAddRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && domains_ != nullptr) {
    delete domains_;
  }
  domains_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* GraphDomainAddRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .esriPBuffer.EsriTypes.Domain domains = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_domains(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GraphDomainAddRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:esriPBuffer.graph.GraphDomainAddRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .esriPBuffer.EsriTypes.Domain domains = 1;
  if (this->has_domains()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::domains(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:esriPBuffer.graph.GraphDomainAddRequest)
  return target;
}

size_t GraphDomainAddRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:esriPBuffer.graph.GraphDomainAddRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .esriPBuffer.EsriTypes.Domain domains = 1;
  if (this->has_domains()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *domains_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GraphDomainAddRequest::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const GraphDomainAddRequest*>(
      &from));
}

void GraphDomainAddRequest::MergeFrom(const GraphDomainAddRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:esriPBuffer.graph.GraphDomainAddRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_domains()) {
    _internal_mutable_domains()->::esriPBuffer::EsriTypes_Domain::MergeFrom(from._internal_domains());
  }
}

void GraphDomainAddRequest::CopyFrom(const GraphDomainAddRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:esriPBuffer.graph.GraphDomainAddRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraphDomainAddRequest::IsInitialized() const {
  return true;
}

void GraphDomainAddRequest::InternalSwap(GraphDomainAddRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  swap(domains_, other->domains_);
}

std::string GraphDomainAddRequest::GetTypeName() const {
  return "esriPBuffer.graph.GraphDomainAddRequest";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace graph
}  // namespace esriPBuffer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::esriPBuffer::graph::GraphDomainAddRequest* Arena::CreateMaybeMessage< ::esriPBuffer::graph::GraphDomainAddRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::esriPBuffer::graph::GraphDomainAddRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
