// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: esriPBuffer/graph/AddNamedTypesResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "esriPBuffer/graph/EsriGraphTypes.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto EXT_CLASS
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct EXT_CLASS TableStruct_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace esriPBuffer {
namespace graph {
class GraphNamedObjectTypeAddResult;
class GraphNamedObjectTypeAddResultDefaultTypeInternal;
EXT_CLASS extern GraphNamedObjectTypeAddResultDefaultTypeInternal _GraphNamedObjectTypeAddResult_default_instance_;
class GraphNamedObjectTypeAddsResponse;
class GraphNamedObjectTypeAddsResponseDefaultTypeInternal;
EXT_CLASS extern GraphNamedObjectTypeAddsResponseDefaultTypeInternal _GraphNamedObjectTypeAddsResponse_default_instance_;
}  // namespace graph
}  // namespace esriPBuffer
PROTOBUF_NAMESPACE_OPEN
template<> EXT_CLASS ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* Arena::CreateMaybeMessage<::esriPBuffer::graph::GraphNamedObjectTypeAddResult>(Arena*);
template<> EXT_CLASS ::esriPBuffer::graph::GraphNamedObjectTypeAddsResponse* Arena::CreateMaybeMessage<::esriPBuffer::graph::GraphNamedObjectTypeAddsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace esriPBuffer {
namespace graph {

// ===================================================================

class EXT_CLASS GraphNamedObjectTypeAddResult PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:esriPBuffer.graph.GraphNamedObjectTypeAddResult) */ {
 public:
  inline GraphNamedObjectTypeAddResult() : GraphNamedObjectTypeAddResult(nullptr) {}
  virtual ~GraphNamedObjectTypeAddResult();

  GraphNamedObjectTypeAddResult(const GraphNamedObjectTypeAddResult& from);
  GraphNamedObjectTypeAddResult(GraphNamedObjectTypeAddResult&& from) noexcept
    : GraphNamedObjectTypeAddResult() {
    *this = ::std::move(from);
  }

  inline GraphNamedObjectTypeAddResult& operator=(const GraphNamedObjectTypeAddResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphNamedObjectTypeAddResult& operator=(GraphNamedObjectTypeAddResult&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GraphNamedObjectTypeAddResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphNamedObjectTypeAddResult* internal_default_instance() {
    return reinterpret_cast<const GraphNamedObjectTypeAddResult*>(
               &_GraphNamedObjectTypeAddResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GraphNamedObjectTypeAddResult& a, GraphNamedObjectTypeAddResult& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphNamedObjectTypeAddResult* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphNamedObjectTypeAddResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphNamedObjectTypeAddResult* New() const final {
    return CreateMaybeMessage<GraphNamedObjectTypeAddResult>(nullptr);
  }

  GraphNamedObjectTypeAddResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphNamedObjectTypeAddResult>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const GraphNamedObjectTypeAddResult& from);
  void MergeFrom(const GraphNamedObjectTypeAddResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GraphNamedObjectTypeAddResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esriPBuffer.graph.GraphNamedObjectTypeAddResult";
  }
  protected:
  explicit GraphNamedObjectTypeAddResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .esriPBuffer.graph.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::esriPBuffer::graph::Error& error() const;
  ::esriPBuffer::graph::Error* release_error();
  ::esriPBuffer::graph::Error* mutable_error();
  void set_allocated_error(::esriPBuffer::graph::Error* error);
  private:
  const ::esriPBuffer::graph::Error& _internal_error() const;
  ::esriPBuffer::graph::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::esriPBuffer::graph::Error* error);
  ::esriPBuffer::graph::Error* unsafe_arena_release_error();

  // @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphNamedObjectTypeAddResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::esriPBuffer::graph::Error* error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto;
};
// -------------------------------------------------------------------

class EXT_CLASS GraphNamedObjectTypeAddsResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse) */ {
 public:
  inline GraphNamedObjectTypeAddsResponse() : GraphNamedObjectTypeAddsResponse(nullptr) {}
  virtual ~GraphNamedObjectTypeAddsResponse();

  GraphNamedObjectTypeAddsResponse(const GraphNamedObjectTypeAddsResponse& from);
  GraphNamedObjectTypeAddsResponse(GraphNamedObjectTypeAddsResponse&& from) noexcept
    : GraphNamedObjectTypeAddsResponse() {
    *this = ::std::move(from);
  }

  inline GraphNamedObjectTypeAddsResponse& operator=(const GraphNamedObjectTypeAddsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphNamedObjectTypeAddsResponse& operator=(GraphNamedObjectTypeAddsResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GraphNamedObjectTypeAddsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphNamedObjectTypeAddsResponse* internal_default_instance() {
    return reinterpret_cast<const GraphNamedObjectTypeAddsResponse*>(
               &_GraphNamedObjectTypeAddsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GraphNamedObjectTypeAddsResponse& a, GraphNamedObjectTypeAddsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphNamedObjectTypeAddsResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphNamedObjectTypeAddsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphNamedObjectTypeAddsResponse* New() const final {
    return CreateMaybeMessage<GraphNamedObjectTypeAddsResponse>(nullptr);
  }

  GraphNamedObjectTypeAddsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphNamedObjectTypeAddsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const GraphNamedObjectTypeAddsResponse& from);
  void MergeFrom(const GraphNamedObjectTypeAddsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GraphNamedObjectTypeAddsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esriPBuffer.graph.GraphNamedObjectTypeAddsResponse";
  }
  protected:
  explicit GraphNamedObjectTypeAddsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityAddResultsFieldNumber = 2,
    kRelationshipAddResultsFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated .esriPBuffer.graph.GraphNamedObjectTypeAddResult entity_add_results = 2;
  int entity_add_results_size() const;
  private:
  int _internal_entity_add_results_size() const;
  public:
  void clear_entity_add_results();
  ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* mutable_entity_add_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >*
      mutable_entity_add_results();
  private:
  const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& _internal_entity_add_results(int index) const;
  ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* _internal_add_entity_add_results();
  public:
  const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& entity_add_results(int index) const;
  ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* add_entity_add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >&
      entity_add_results() const;

  // repeated .esriPBuffer.graph.GraphNamedObjectTypeAddResult relationship_add_results = 3;
  int relationship_add_results_size() const;
  private:
  int _internal_relationship_add_results_size() const;
  public:
  void clear_relationship_add_results();
  ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* mutable_relationship_add_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >*
      mutable_relationship_add_results();
  private:
  const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& _internal_relationship_add_results(int index) const;
  ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* _internal_add_relationship_add_results();
  public:
  const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& relationship_add_results(int index) const;
  ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* add_relationship_add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >&
      relationship_add_results() const;

  // .esriPBuffer.graph.Error error = 1;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::esriPBuffer::graph::Error& error() const;
  ::esriPBuffer::graph::Error* release_error();
  ::esriPBuffer::graph::Error* mutable_error();
  void set_allocated_error(::esriPBuffer::graph::Error* error);
  private:
  const ::esriPBuffer::graph::Error& _internal_error() const;
  ::esriPBuffer::graph::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::esriPBuffer::graph::Error* error);
  ::esriPBuffer::graph::Error* unsafe_arena_release_error();

  // @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult > entity_add_results_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult > relationship_add_results_;
  ::esriPBuffer::graph::Error* error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraphNamedObjectTypeAddResult

// string name = 1;
inline void GraphNamedObjectTypeAddResult::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GraphNamedObjectTypeAddResult::name() const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
  return _internal_name();
}
inline void GraphNamedObjectTypeAddResult::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
}
inline std::string* GraphNamedObjectTypeAddResult::mutable_name() {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
  return _internal_mutable_name();
}
inline const std::string& GraphNamedObjectTypeAddResult::_internal_name() const {
  return name_.Get();
}
inline void GraphNamedObjectTypeAddResult::_internal_set_name(const std::string& value) {
  
  name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GraphNamedObjectTypeAddResult::set_name(std::string&& value) {
  
  name_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
}
inline void GraphNamedObjectTypeAddResult::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
}
inline void GraphNamedObjectTypeAddResult::set_name(const char* value,
    size_t size) {
  
  name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
}
inline std::string* GraphNamedObjectTypeAddResult::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GraphNamedObjectTypeAddResult::release_name() {
  // @@protoc_insertion_point(field_release:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraphNamedObjectTypeAddResult::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:esriPBuffer.graph.GraphNamedObjectTypeAddResult.name)
}

// .esriPBuffer.graph.Error error = 2;
inline bool GraphNamedObjectTypeAddResult::_internal_has_error() const {
  return this != internal_default_instance() && error_ != nullptr;
}
inline bool GraphNamedObjectTypeAddResult::has_error() const {
  return _internal_has_error();
}
inline const ::esriPBuffer::graph::Error& GraphNamedObjectTypeAddResult::_internal_error() const {
  const ::esriPBuffer::graph::Error* p = error_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esriPBuffer::graph::Error*>(
      &::esriPBuffer::graph::_Error_default_instance_);
}
inline const ::esriPBuffer::graph::Error& GraphNamedObjectTypeAddResult::error() const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphNamedObjectTypeAddResult.error)
  return _internal_error();
}
inline void GraphNamedObjectTypeAddResult::unsafe_arena_set_allocated_error(
    ::esriPBuffer::graph::Error* error) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  error_ = error;
  if (error) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esriPBuffer.graph.GraphNamedObjectTypeAddResult.error)
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddResult::release_error() {
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddResult::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:esriPBuffer.graph.GraphNamedObjectTypeAddResult.error)
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddResult::_internal_mutable_error() {
  
  if (error_ == nullptr) {
    auto* p = CreateMaybeMessage<::esriPBuffer::graph::Error>(GetArena());
    error_ = p;
  }
  return error_;
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddResult::mutable_error() {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphNamedObjectTypeAddResult.error)
  return _internal_mutable_error();
}
inline void GraphNamedObjectTypeAddResult::set_allocated_error(::esriPBuffer::graph::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error)->GetArena();
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:esriPBuffer.graph.GraphNamedObjectTypeAddResult.error)
}

// -------------------------------------------------------------------

// GraphNamedObjectTypeAddsResponse

// .esriPBuffer.graph.Error error = 1;
inline bool GraphNamedObjectTypeAddsResponse::_internal_has_error() const {
  return this != internal_default_instance() && error_ != nullptr;
}
inline bool GraphNamedObjectTypeAddsResponse::has_error() const {
  return _internal_has_error();
}
inline const ::esriPBuffer::graph::Error& GraphNamedObjectTypeAddsResponse::_internal_error() const {
  const ::esriPBuffer::graph::Error* p = error_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esriPBuffer::graph::Error*>(
      &::esriPBuffer::graph::_Error_default_instance_);
}
inline const ::esriPBuffer::graph::Error& GraphNamedObjectTypeAddsResponse::error() const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.error)
  return _internal_error();
}
inline void GraphNamedObjectTypeAddsResponse::unsafe_arena_set_allocated_error(
    ::esriPBuffer::graph::Error* error) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  error_ = error;
  if (error) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.error)
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddsResponse::release_error() {
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddsResponse::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.error)
  
  ::esriPBuffer::graph::Error* temp = error_;
  error_ = nullptr;
  return temp;
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddsResponse::_internal_mutable_error() {
  
  if (error_ == nullptr) {
    auto* p = CreateMaybeMessage<::esriPBuffer::graph::Error>(GetArena());
    error_ = p;
  }
  return error_;
}
inline ::esriPBuffer::graph::Error* GraphNamedObjectTypeAddsResponse::mutable_error() {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.error)
  return _internal_mutable_error();
}
inline void GraphNamedObjectTypeAddsResponse::set_allocated_error(::esriPBuffer::graph::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(error_);
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error)->GetArena();
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.error)
}

// repeated .esriPBuffer.graph.GraphNamedObjectTypeAddResult entity_add_results = 2;
inline int GraphNamedObjectTypeAddsResponse::_internal_entity_add_results_size() const {
  return entity_add_results_.size();
}
inline int GraphNamedObjectTypeAddsResponse::entity_add_results_size() const {
  return _internal_entity_add_results_size();
}
inline void GraphNamedObjectTypeAddsResponse::clear_entity_add_results() {
  entity_add_results_.Clear();
}
inline ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* GraphNamedObjectTypeAddsResponse::mutable_entity_add_results(int index) {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.entity_add_results)
  return entity_add_results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >*
GraphNamedObjectTypeAddsResponse::mutable_entity_add_results() {
  // @@protoc_insertion_point(field_mutable_list:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.entity_add_results)
  return &entity_add_results_;
}
inline const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& GraphNamedObjectTypeAddsResponse::_internal_entity_add_results(int index) const {
  return entity_add_results_.Get(index);
}
inline const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& GraphNamedObjectTypeAddsResponse::entity_add_results(int index) const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.entity_add_results)
  return _internal_entity_add_results(index);
}
inline ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* GraphNamedObjectTypeAddsResponse::_internal_add_entity_add_results() {
  return entity_add_results_.Add();
}
inline ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* GraphNamedObjectTypeAddsResponse::add_entity_add_results() {
  // @@protoc_insertion_point(field_add:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.entity_add_results)
  return _internal_add_entity_add_results();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >&
GraphNamedObjectTypeAddsResponse::entity_add_results() const {
  // @@protoc_insertion_point(field_list:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.entity_add_results)
  return entity_add_results_;
}

// repeated .esriPBuffer.graph.GraphNamedObjectTypeAddResult relationship_add_results = 3;
inline int GraphNamedObjectTypeAddsResponse::_internal_relationship_add_results_size() const {
  return relationship_add_results_.size();
}
inline int GraphNamedObjectTypeAddsResponse::relationship_add_results_size() const {
  return _internal_relationship_add_results_size();
}
inline void GraphNamedObjectTypeAddsResponse::clear_relationship_add_results() {
  relationship_add_results_.Clear();
}
inline ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* GraphNamedObjectTypeAddsResponse::mutable_relationship_add_results(int index) {
  // @@protoc_insertion_point(field_mutable:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.relationship_add_results)
  return relationship_add_results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >*
GraphNamedObjectTypeAddsResponse::mutable_relationship_add_results() {
  // @@protoc_insertion_point(field_mutable_list:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.relationship_add_results)
  return &relationship_add_results_;
}
inline const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& GraphNamedObjectTypeAddsResponse::_internal_relationship_add_results(int index) const {
  return relationship_add_results_.Get(index);
}
inline const ::esriPBuffer::graph::GraphNamedObjectTypeAddResult& GraphNamedObjectTypeAddsResponse::relationship_add_results(int index) const {
  // @@protoc_insertion_point(field_get:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.relationship_add_results)
  return _internal_relationship_add_results(index);
}
inline ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* GraphNamedObjectTypeAddsResponse::_internal_add_relationship_add_results() {
  return relationship_add_results_.Add();
}
inline ::esriPBuffer::graph::GraphNamedObjectTypeAddResult* GraphNamedObjectTypeAddsResponse::add_relationship_add_results() {
  // @@protoc_insertion_point(field_add:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.relationship_add_results)
  return _internal_add_relationship_add_results();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esriPBuffer::graph::GraphNamedObjectTypeAddResult >&
GraphNamedObjectTypeAddsResponse::relationship_add_results() const {
  // @@protoc_insertion_point(field_list:esriPBuffer.graph.GraphNamedObjectTypeAddsResponse.relationship_add_results)
  return relationship_add_results_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace graph
}  // namespace esriPBuffer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_esriPBuffer_2fgraph_2fAddNamedTypesResponse_2eproto
