# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/AddIndexesRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer import EsriTypes_pb2 as esriPBuffer_dot_EsriTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='esriPBuffer/graph/AddIndexesRequest.proto',
  package='esriPBuffer.graph',
  syntax='proto3',
  serialized_options=b'\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)esriPBuffer/graph/AddIndexesRequest.proto\x12\x11\x65sriPBuffer.graph\x1a\x1b\x65sriPBuffer/EsriTypes.proto\"Y\n\x1dGraphPropertyIndexAddsRequest\x12\x38\n\rfield_indexes\x18\x01 \x03(\x0b\x32!.esriPBuffer.EsriTypes.FieldIndexB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[esriPBuffer_dot_EsriTypes__pb2.DESCRIPTOR,])




_GRAPHPROPERTYINDEXADDSREQUEST = _descriptor.Descriptor(
  name='GraphPropertyIndexAddsRequest',
  full_name='esriPBuffer.graph.GraphPropertyIndexAddsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_indexes', full_name='esriPBuffer.graph.GraphPropertyIndexAddsRequest.field_indexes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=182,
)

_GRAPHPROPERTYINDEXADDSREQUEST.fields_by_name['field_indexes'].message_type = esriPBuffer_dot_EsriTypes__pb2._ESRITYPES_FIELDINDEX
DESCRIPTOR.message_types_by_name['GraphPropertyIndexAddsRequest'] = _GRAPHPROPERTYINDEXADDSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphPropertyIndexAddsRequest = _reflection.GeneratedProtocolMessageType('GraphPropertyIndexAddsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHPROPERTYINDEXADDSREQUEST,
  '__module__' : 'esriPBuffer.graph.AddIndexesRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphPropertyIndexAddsRequest)
  })
_sym_db.RegisterMessage(GraphPropertyIndexAddsRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
