# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/AddIndexesResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='esriPBuffer/graph/AddIndexesResponse.proto',
  package='esriPBuffer.graph',
  syntax='proto3',
  serialized_options=b'\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*esriPBuffer/graph/AddIndexesResponse.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/EsriGraphTypes.proto\"T\n\x1bGraphPropertyIndexAddResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\"\x94\x01\n\x1eGraphPropertyIndexAddsResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12I\n\x11index_add_results\x18\x02 \x03(\x0b\x32..esriPBuffer.graph.GraphPropertyIndexAddResultB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2.DESCRIPTOR,])




_GRAPHPROPERTYINDEXADDRESULT = _descriptor.Descriptor(
  name='GraphPropertyIndexAddResult',
  full_name='esriPBuffer.graph.GraphPropertyIndexAddResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='esriPBuffer.graph.GraphPropertyIndexAddResult.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='esriPBuffer.graph.GraphPropertyIndexAddResult.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=189,
)


_GRAPHPROPERTYINDEXADDSRESPONSE = _descriptor.Descriptor(
  name='GraphPropertyIndexAddsResponse',
  full_name='esriPBuffer.graph.GraphPropertyIndexAddsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='esriPBuffer.graph.GraphPropertyIndexAddsResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index_add_results', full_name='esriPBuffer.graph.GraphPropertyIndexAddsResponse.index_add_results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=340,
)

_GRAPHPROPERTYINDEXADDRESULT.fields_by_name['error'].message_type = esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2._ERROR
_GRAPHPROPERTYINDEXADDSRESPONSE.fields_by_name['error'].message_type = esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2._ERROR
_GRAPHPROPERTYINDEXADDSRESPONSE.fields_by_name['index_add_results'].message_type = _GRAPHPROPERTYINDEXADDRESULT
DESCRIPTOR.message_types_by_name['GraphPropertyIndexAddResult'] = _GRAPHPROPERTYINDEXADDRESULT
DESCRIPTOR.message_types_by_name['GraphPropertyIndexAddsResponse'] = _GRAPHPROPERTYINDEXADDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphPropertyIndexAddResult = _reflection.GeneratedProtocolMessageType('GraphPropertyIndexAddResult', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHPROPERTYINDEXADDRESULT,
  '__module__' : 'esriPBuffer.graph.AddIndexesResponse_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphPropertyIndexAddResult)
  })
_sym_db.RegisterMessage(GraphPropertyIndexAddResult)

GraphPropertyIndexAddsResponse = _reflection.GeneratedProtocolMessageType('GraphPropertyIndexAddsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHPROPERTYINDEXADDSRESPONSE,
  '__module__' : 'esriPBuffer.graph.AddIndexesResponse_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphPropertyIndexAddsResponse)
  })
_sym_db.RegisterMessage(GraphPropertyIndexAddsResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
