# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/DeleteIndexesResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='esriPBuffer/graph/DeleteIndexesResponse.proto',
  package='esriPBuffer.graph',
  syntax='proto3',
  serialized_options=b'\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-esriPBuffer/graph/DeleteIndexesResponse.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/EsriGraphTypes.proto\"O\n\x16GraphIndexDeleteResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\"\x8c\x01\n\x18GraphIndexDeleteResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12G\n\x14index_delete_results\x18\x02 \x03(\x0b\x32).esriPBuffer.graph.GraphIndexDeleteResultB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2.DESCRIPTOR,])




_GRAPHINDEXDELETERESULT = _descriptor.Descriptor(
  name='GraphIndexDeleteResult',
  full_name='esriPBuffer.graph.GraphIndexDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='esriPBuffer.graph.GraphIndexDeleteResult.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='esriPBuffer.graph.GraphIndexDeleteResult.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=187,
)


_GRAPHINDEXDELETERESPONSE = _descriptor.Descriptor(
  name='GraphIndexDeleteResponse',
  full_name='esriPBuffer.graph.GraphIndexDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='esriPBuffer.graph.GraphIndexDeleteResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index_delete_results', full_name='esriPBuffer.graph.GraphIndexDeleteResponse.index_delete_results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=330,
)

_GRAPHINDEXDELETERESULT.fields_by_name['error'].message_type = esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2._ERROR
_GRAPHINDEXDELETERESPONSE.fields_by_name['error'].message_type = esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2._ERROR
_GRAPHINDEXDELETERESPONSE.fields_by_name['index_delete_results'].message_type = _GRAPHINDEXDELETERESULT
DESCRIPTOR.message_types_by_name['GraphIndexDeleteResult'] = _GRAPHINDEXDELETERESULT
DESCRIPTOR.message_types_by_name['GraphIndexDeleteResponse'] = _GRAPHINDEXDELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphIndexDeleteResult = _reflection.GeneratedProtocolMessageType('GraphIndexDeleteResult', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHINDEXDELETERESULT,
  '__module__' : 'esriPBuffer.graph.DeleteIndexesResponse_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphIndexDeleteResult)
  })
_sym_db.RegisterMessage(GraphIndexDeleteResult)

GraphIndexDeleteResponse = _reflection.GeneratedProtocolMessageType('GraphIndexDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHINDEXDELETERESPONSE,
  '__module__' : 'esriPBuffer.graph.DeleteIndexesResponse_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphIndexDeleteResponse)
  })
_sym_db.RegisterMessage(GraphIndexDeleteResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
