# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/DeleteFieldRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='esriPBuffer/graph/DeleteFieldRequest.proto',
  package='esriPBuffer.graph',
  syntax='proto3',
  serialized_options=b'\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*esriPBuffer/graph/DeleteFieldRequest.proto\x12\x11\x65sriPBuffer.graph\"*\n\x1aGraphPropertyDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\tB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)




_GRAPHPROPERTYDELETEREQUEST = _descriptor.Descriptor(
  name='GraphPropertyDeleteRequest',
  full_name='esriPBuffer.graph.GraphPropertyDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='esriPBuffer.graph.GraphPropertyDeleteRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['GraphPropertyDeleteRequest'] = _GRAPHPROPERTYDELETEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphPropertyDeleteRequest = _reflection.GeneratedProtocolMessageType('GraphPropertyDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHPROPERTYDELETEREQUEST,
  '__module__' : 'esriPBuffer.graph.DeleteFieldRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphPropertyDeleteRequest)
  })
_sym_db.RegisterMessage(GraphPropertyDeleteRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
