# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/UpdateNamedTypeRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import DataModelTypes_pb2 as esriPBuffer_dot_graph_dot_DataModelTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='esriPBuffer/graph/UpdateNamedTypeRequest.proto',
  package='esriPBuffer.graph',
  syntax='proto3',
  serialized_options=b'\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.esriPBuffer/graph/UpdateNamedTypeRequest.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/DataModelTypes.proto\"\xca\x01\n!GraphNamedObjectTypeUpdateRequest\x12\x41\n\rentity_update\x18\x01 \x01(\x0b\x32(.esriPBuffer.graph.GraphEntityTypeUpdateH\x00\x12M\n\x13relationship_update\x18\x02 \x01(\x0b\x32..esriPBuffer.graph.GraphRelationshipTypeUpdateH\x00\x42\x13\n\x11named_type_update\"U\n\x13NamedObjectTypeMask\x12\x13\n\x0bupdate_name\x18\x01 \x01(\x08\x12\x14\n\x0cupdate_alias\x18\x02 \x01(\x08\x12\x13\n\x0bupdate_role\x18\x04 \x01(\x08\"\x81\x01\n\x15GraphEntityTypeUpdate\x12\x34\n\x04mask\x18\x01 \x01(\x0b\x32&.esriPBuffer.graph.NamedObjectTypeMask\x12\x32\n\x0b\x65ntity_type\x18\x02 \x01(\x0b\x32\x1d.esriPBuffer.graph.EntityType\"\x96\x02\n\x14RelationshipTypeMask\x12\x46\n\x16named_object_type_mask\x18\x01 \x01(\x0b\x32&.esriPBuffer.graph.NamedObjectTypeMask\x12!\n\x17\x61\x64\x64_origin_entity_types\x18\x02 \x01(\x08H\x00\x12$\n\x1a\x64\x65lete_origin_entity_types\x18\x03 \x01(\x08H\x00\x12\x1f\n\x15\x61\x64\x64_dest_entity_types\x18\x04 \x01(\x08H\x01\x12\"\n\x18\x64\x65lete_dest_entity_types\x18\x05 \x01(\x08H\x01\x42\x14\n\x12origin_entity_typeB\x12\n\x10\x64\x65st_entity_type\"\x94\x01\n\x1bGraphRelationshipTypeUpdate\x12\x35\n\x04mask\x18\x01 \x01(\x0b\x32\'.esriPBuffer.graph.RelationshipTypeMask\x12>\n\x11relationship_type\x18\x02 \x01(\x0b\x32#.esriPBuffer.graph.RelationshipTypeB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[esriPBuffer_dot_graph_dot_DataModelTypes__pb2.DESCRIPTOR,])




_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST = _descriptor.Descriptor(
  name='GraphNamedObjectTypeUpdateRequest',
  full_name='esriPBuffer.graph.GraphNamedObjectTypeUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_update', full_name='esriPBuffer.graph.GraphNamedObjectTypeUpdateRequest.entity_update', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relationship_update', full_name='esriPBuffer.graph.GraphNamedObjectTypeUpdateRequest.relationship_update', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='named_type_update', full_name='esriPBuffer.graph.GraphNamedObjectTypeUpdateRequest.named_type_update',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=110,
  serialized_end=312,
)


_NAMEDOBJECTTYPEMASK = _descriptor.Descriptor(
  name='NamedObjectTypeMask',
  full_name='esriPBuffer.graph.NamedObjectTypeMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_name', full_name='esriPBuffer.graph.NamedObjectTypeMask.update_name', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_alias', full_name='esriPBuffer.graph.NamedObjectTypeMask.update_alias', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_role', full_name='esriPBuffer.graph.NamedObjectTypeMask.update_role', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=399,
)


_GRAPHENTITYTYPEUPDATE = _descriptor.Descriptor(
  name='GraphEntityTypeUpdate',
  full_name='esriPBuffer.graph.GraphEntityTypeUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mask', full_name='esriPBuffer.graph.GraphEntityTypeUpdate.mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='esriPBuffer.graph.GraphEntityTypeUpdate.entity_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=531,
)


_RELATIONSHIPTYPEMASK = _descriptor.Descriptor(
  name='RelationshipTypeMask',
  full_name='esriPBuffer.graph.RelationshipTypeMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='named_object_type_mask', full_name='esriPBuffer.graph.RelationshipTypeMask.named_object_type_mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_origin_entity_types', full_name='esriPBuffer.graph.RelationshipTypeMask.add_origin_entity_types', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete_origin_entity_types', full_name='esriPBuffer.graph.RelationshipTypeMask.delete_origin_entity_types', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_dest_entity_types', full_name='esriPBuffer.graph.RelationshipTypeMask.add_dest_entity_types', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete_dest_entity_types', full_name='esriPBuffer.graph.RelationshipTypeMask.delete_dest_entity_types', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='origin_entity_type', full_name='esriPBuffer.graph.RelationshipTypeMask.origin_entity_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='dest_entity_type', full_name='esriPBuffer.graph.RelationshipTypeMask.dest_entity_type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=534,
  serialized_end=812,
)


_GRAPHRELATIONSHIPTYPEUPDATE = _descriptor.Descriptor(
  name='GraphRelationshipTypeUpdate',
  full_name='esriPBuffer.graph.GraphRelationshipTypeUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mask', full_name='esriPBuffer.graph.GraphRelationshipTypeUpdate.mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relationship_type', full_name='esriPBuffer.graph.GraphRelationshipTypeUpdate.relationship_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=815,
  serialized_end=963,
)

_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.fields_by_name['entity_update'].message_type = _GRAPHENTITYTYPEUPDATE
_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.fields_by_name['relationship_update'].message_type = _GRAPHRELATIONSHIPTYPEUPDATE
_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.oneofs_by_name['named_type_update'].fields.append(
  _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.fields_by_name['entity_update'])
_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.fields_by_name['entity_update'].containing_oneof = _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.oneofs_by_name['named_type_update']
_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.oneofs_by_name['named_type_update'].fields.append(
  _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.fields_by_name['relationship_update'])
_GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.fields_by_name['relationship_update'].containing_oneof = _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST.oneofs_by_name['named_type_update']
_GRAPHENTITYTYPEUPDATE.fields_by_name['mask'].message_type = _NAMEDOBJECTTYPEMASK
_GRAPHENTITYTYPEUPDATE.fields_by_name['entity_type'].message_type = esriPBuffer_dot_graph_dot_DataModelTypes__pb2._ENTITYTYPE
_RELATIONSHIPTYPEMASK.fields_by_name['named_object_type_mask'].message_type = _NAMEDOBJECTTYPEMASK
_RELATIONSHIPTYPEMASK.oneofs_by_name['origin_entity_type'].fields.append(
  _RELATIONSHIPTYPEMASK.fields_by_name['add_origin_entity_types'])
_RELATIONSHIPTYPEMASK.fields_by_name['add_origin_entity_types'].containing_oneof = _RELATIONSHIPTYPEMASK.oneofs_by_name['origin_entity_type']
_RELATIONSHIPTYPEMASK.oneofs_by_name['origin_entity_type'].fields.append(
  _RELATIONSHIPTYPEMASK.fields_by_name['delete_origin_entity_types'])
_RELATIONSHIPTYPEMASK.fields_by_name['delete_origin_entity_types'].containing_oneof = _RELATIONSHIPTYPEMASK.oneofs_by_name['origin_entity_type']
_RELATIONSHIPTYPEMASK.oneofs_by_name['dest_entity_type'].fields.append(
  _RELATIONSHIPTYPEMASK.fields_by_name['add_dest_entity_types'])
_RELATIONSHIPTYPEMASK.fields_by_name['add_dest_entity_types'].containing_oneof = _RELATIONSHIPTYPEMASK.oneofs_by_name['dest_entity_type']
_RELATIONSHIPTYPEMASK.oneofs_by_name['dest_entity_type'].fields.append(
  _RELATIONSHIPTYPEMASK.fields_by_name['delete_dest_entity_types'])
_RELATIONSHIPTYPEMASK.fields_by_name['delete_dest_entity_types'].containing_oneof = _RELATIONSHIPTYPEMASK.oneofs_by_name['dest_entity_type']
_GRAPHRELATIONSHIPTYPEUPDATE.fields_by_name['mask'].message_type = _RELATIONSHIPTYPEMASK
_GRAPHRELATIONSHIPTYPEUPDATE.fields_by_name['relationship_type'].message_type = esriPBuffer_dot_graph_dot_DataModelTypes__pb2._RELATIONSHIPTYPE
DESCRIPTOR.message_types_by_name['GraphNamedObjectTypeUpdateRequest'] = _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST
DESCRIPTOR.message_types_by_name['NamedObjectTypeMask'] = _NAMEDOBJECTTYPEMASK
DESCRIPTOR.message_types_by_name['GraphEntityTypeUpdate'] = _GRAPHENTITYTYPEUPDATE
DESCRIPTOR.message_types_by_name['RelationshipTypeMask'] = _RELATIONSHIPTYPEMASK
DESCRIPTOR.message_types_by_name['GraphRelationshipTypeUpdate'] = _GRAPHRELATIONSHIPTYPEUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphNamedObjectTypeUpdateRequest = _reflection.GeneratedProtocolMessageType('GraphNamedObjectTypeUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST,
  '__module__' : 'esriPBuffer.graph.UpdateNamedTypeRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphNamedObjectTypeUpdateRequest)
  })
_sym_db.RegisterMessage(GraphNamedObjectTypeUpdateRequest)

NamedObjectTypeMask = _reflection.GeneratedProtocolMessageType('NamedObjectTypeMask', (_message.Message,), {
  'DESCRIPTOR' : _NAMEDOBJECTTYPEMASK,
  '__module__' : 'esriPBuffer.graph.UpdateNamedTypeRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.NamedObjectTypeMask)
  })
_sym_db.RegisterMessage(NamedObjectTypeMask)

GraphEntityTypeUpdate = _reflection.GeneratedProtocolMessageType('GraphEntityTypeUpdate', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHENTITYTYPEUPDATE,
  '__module__' : 'esriPBuffer.graph.UpdateNamedTypeRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphEntityTypeUpdate)
  })
_sym_db.RegisterMessage(GraphEntityTypeUpdate)

RelationshipTypeMask = _reflection.GeneratedProtocolMessageType('RelationshipTypeMask', (_message.Message,), {
  'DESCRIPTOR' : _RELATIONSHIPTYPEMASK,
  '__module__' : 'esriPBuffer.graph.UpdateNamedTypeRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.RelationshipTypeMask)
  })
_sym_db.RegisterMessage(RelationshipTypeMask)

GraphRelationshipTypeUpdate = _reflection.GeneratedProtocolMessageType('GraphRelationshipTypeUpdate', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHRELATIONSHIPTYPEUPDATE,
  '__module__' : 'esriPBuffer.graph.UpdateNamedTypeRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.GraphRelationshipTypeUpdate)
  })
_sym_db.RegisterMessage(GraphRelationshipTypeUpdate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
