# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/UpdateDomainRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer import EsriTypes_pb2 as esriPBuffer_dot_EsriTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='esriPBuffer/graph/UpdateDomainRequest.proto',
  package='esriPBuffer.graph',
  syntax='proto3',
  serialized_options=b'\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+esriPBuffer/graph/UpdateDomainRequest.proto\x12\x11\x65sriPBuffer.graph\x1a\x1b\x65sriPBuffer/EsriTypes.proto\"\xa2\x01\n\nDomainMask\x12\x13\n\x0bupdate_type\x18\x01 \x01(\x08\x12\x13\n\x0bupdate_name\x18\x02 \x01(\x08\x12\x15\n\rupdate_domain\x18\x03 \x01(\x08\x12\x19\n\x11update_field_type\x18\x04 \x01(\x08\x12\x1b\n\x13update_merge_policy\x18\x05 \x01(\x08\x12\x1b\n\x13update_split_policy\x18\x06 \x01(\x08\"q\n\x13\x44omainUpdateRequest\x12+\n\x04mask\x18\x01 \x01(\x0b\x32\x1d.esriPBuffer.graph.DomainMask\x12-\n\x06\x64omain\x18\x02 \x01(\x0b\x32\x1d.esriPBuffer.EsriTypes.DomainB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[esriPBuffer_dot_EsriTypes__pb2.DESCRIPTOR,])




_DOMAINMASK = _descriptor.Descriptor(
  name='DomainMask',
  full_name='esriPBuffer.graph.DomainMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_type', full_name='esriPBuffer.graph.DomainMask.update_type', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_name', full_name='esriPBuffer.graph.DomainMask.update_name', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_domain', full_name='esriPBuffer.graph.DomainMask.update_domain', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_field_type', full_name='esriPBuffer.graph.DomainMask.update_field_type', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_merge_policy', full_name='esriPBuffer.graph.DomainMask.update_merge_policy', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_split_policy', full_name='esriPBuffer.graph.DomainMask.update_split_policy', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=258,
)


_DOMAINUPDATEREQUEST = _descriptor.Descriptor(
  name='DomainUpdateRequest',
  full_name='esriPBuffer.graph.DomainUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mask', full_name='esriPBuffer.graph.DomainUpdateRequest.mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='esriPBuffer.graph.DomainUpdateRequest.domain', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=373,
)

_DOMAINUPDATEREQUEST.fields_by_name['mask'].message_type = _DOMAINMASK
_DOMAINUPDATEREQUEST.fields_by_name['domain'].message_type = esriPBuffer_dot_EsriTypes__pb2._ESRITYPES_DOMAIN
DESCRIPTOR.message_types_by_name['DomainMask'] = _DOMAINMASK
DESCRIPTOR.message_types_by_name['DomainUpdateRequest'] = _DOMAINUPDATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DomainMask = _reflection.GeneratedProtocolMessageType('DomainMask', (_message.Message,), {
  'DESCRIPTOR' : _DOMAINMASK,
  '__module__' : 'esriPBuffer.graph.UpdateDomainRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.DomainMask)
  })
_sym_db.RegisterMessage(DomainMask)

DomainUpdateRequest = _reflection.GeneratedProtocolMessageType('DomainUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOMAINUPDATEREQUEST,
  '__module__' : 'esriPBuffer.graph.UpdateDomainRequest_pb2'
  # @@protoc_insertion_point(class_scope:esriPBuffer.graph.DomainUpdateRequest)
  })
_sym_db.RegisterMessage(DomainUpdateRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
